package ca.qc.cgmatane.informatique.monmagasinage.donnees.base;

import ca.qc.cgmatane.informatique.monmagasinage.modele.Produit;
import ca.qc.cgmatane.informatique.monmagasinage.modele.pluriel.Produits;

import java.util.ArrayList;
import java.util.Arrays;

public interface RequeteInsertionProduit {
    final static ArrayList<Produits> tousMesProduits = new ArrayList<Produits>() {{
        add(creeListeProduitFruitsEtLegumes());
        add(creeListeProduitViandeEtVolaille());
        add(creeListeProduitEpicerie());
        add(creeListeProduitLaitiers());
        add(creeListeProduitBoulangerie());
        add(creeListeProduitBoisson());
        add(creeListeProduitColation());
    }};

    /* static Produits creeListeProduitEpicerie() {
        Produits produits = new Produits();
        return produits;
    }
    */
    static Produits creeListeProduitColation() {
        Produits produits = new Produits();
        produits.add(new Produit(1, "Croustilles classiques format familial", 1, 0));
        produits.add(new Produit(2, "Croustilles nature ondulées", 1, 0));
        produits.add(new Produit(3, "Croustilles à l'ancienne originales au sel de mer", 1, 0));
        produits.add(new Produit(4, "Croustilles recette originale", 1, 0));
        produits.add(new Produit(5, "Gâteaux Ah Caramel!™", 1, 0));
        produits.add(new Produit(6, "Chips tortilla au fromage nacho", 1, 0));
        produits.add(new Produit(7, "Gâteaux Jos Louis™ à saveur originale", 1, 0));
        produits.add(new Produit(8, "Croustilles nature", 1, 0));
        produits.add(new Produit(9, "Croustilles barbecue ondulées", 1, 0));
        produits.add(new Produit(10, "Croustilles barbecue", 1, 0));
        produits.add(new Produit(11, "Croustilles Bar-B-Q à l'ancienne format familial", 1, 0));
        produits.add(new Produit(12, "Croustilles tortilla Scoops®", 1, 0));
        produits.add(new Produit(13, "Gâteaux May West™ à saveur originale", 1, 0));
        produits.add(new Produit(14, "Croustilles originales format familial, Ondulées", 1, 0));
        produits.add(new Produit(15, "Arachides grillées à sec délicatement assaisonnées", 1, 0));
        produits.add(new Produit(16, "Croustilles assaisonnées ondulées", 1, 0));
        produits.add(new Produit(21, "Croustilles Bar-B-Q format familial", 1, 0));
        produits.add(new Produit(22, "Croustilles ketchup", 1, 0));
        produits.add(new Produit(23, "Croustilles saveur original", 1, 0));
        produits.add(new Produit(24, "Barre de chocolat, Caramilk", 1, 0));
        produits.add(new Produit(25, "Bâtonnets au fromage", 1, 0));
        produits.add(new Produit(26, "Croustilles nature", 1, 0));
        produits.add(new Produit(27, "Amuse-gueules original mélange fiesta", 1, 0));
        produits.add(new Produit(28, "Croustilles assaisonnées", 1, 0));
        produits.add(new Produit(29, "Craquelins cuits au four à saveur de cheddar, Goldfish", 1, 0));
        produits.add(new Produit(30, "Craquelins aux légumes du jardin, Breton", 1, 0));
        produits.add(new Produit(31, "Guimauves", 1, 0));
        produits.add(new Produit(32, "Grignotines soufflées à saveur de fromage", 1, 0));
        produits.add(new Produit(33, "Croustilles de tortillas rondes", 1, 0));
        produits.add(new Produit(34, "Croustilles à l'ancienne sel de mer et vinaigre de malt", 1, 0));
        produits.add(new Produit(35, "Barre de chocolat, Aero", 1, 0));
        produits.add(new Produit(36, "Croustilles de tortillas style restaurant", 1, 0));
        produits.add(new Produit(41, "Croustilles légèrement salées format familial, Ondulées", 1, 0));
        produits.add(new Produit(42, "Grains de chocolat au lait, Chipits", 1, 0));
        produits.add(new Produit(43, "Compotes aux pommes et poires sans sucre ajouté, Mieux-être", 1, 0));
        produits.add(new Produit(44, "Croustilles crème sure et oignon ondulées", 1, 0));
        produits.add(new Produit(45, "Grignotines à saveur de fromage", 1, 0));
        produits.add(new Produit(46, "Croustilles sel marin et vinaigre de malt", 1, 0));
        produits.add(new Produit(47, "Tablette de chocolat noir 70 % de cacao, Excellence", 1, 0));
        produits.add(new Produit(48, "Biscuits feuille d'érable original", 1, 0));
        produits.add(new Produit(49, "Croustilles à l'ancienne lime et poivre noir", 1, 0));
        produits.add(new Produit(50, "Grains de chocolat pur mi-sucré, Chipits", 1, 0));
        produits.add(new Produit(51, "Pâtisseries feuilletées pomme-framboise Passion Flakie®", 1, 0));
        produits.add(new Produit(52, "Croustilles nature moins de sel", 1, 0));
        produits.add(new Produit(53, "Craquelins au fromage en bâtonnets", 1, 0));
        produits.add(new Produit(54, "Biscuits originaux, Chips Ahoy!", 1, 0));
        produits.add(new Produit(55, "Guimauves miniatures", 1, 0));
        produits.add(new Produit(56, "Craquelins originals, Vinta", 1, 0));
        produits.add(new Produit(61, "Craquelins sandwiches à saveur de fromage, Mini Ritz", 1, 0));
        produits.add(new Produit(62, "Biscuits au beurre garnis de chocolat noir à 70 % de cacao, Célébration", 1, 0));
        produits.add(new Produit(63, "Barre de chocoloat, Oh Henry!", 1, 0));
        produits.add(new Produit(64, "Mélange à gâteau saveur chocolat, Super Moist", 1, 0));
        produits.add(new Produit(65, "Gâteaux éponge billot à la gelée", 1, 0));
        produits.add(new Produit(66, "Compotes aux pommes et fraises sans sucre ajouté, Mieux-être", 1, 0));
        produits.add(new Produit(67, "Compote de pomme non sucrée, Fruitsations", 1, 0));
        produits.add(new Produit(68, "Bâtonnets à la noix de coco enrobés de chocolat, Whippet", 1, 0));
        produits.add(new Produit(69, "Croustilles à l'ancienne bacon et cheddar", 1, 0));
        produits.add(new Produit(70, "Biscuits-sandwichs au chocolat L'original format familial, Oreo", 1, 0));
        produits.add(new Produit(71, "Croustilles BBQ fumé au bois de pommier", 1, 0));
        produits.add(new Produit(72, "Biscuits gaufrettes au café au lait enrobés de chocolat, Célébration", 1, 0));
        produits.add(new Produit(73, "Croustilles de maïs originales", 1, 0));
        produits.add(new Produit(74, "Croustilles sel et poivre", 1, 0));
        produits.add(new Produit(75, "Croustilles ondulées à la poutine", 1, 0));
        produits.add(new Produit(76, "Craquelins de riz au sésame, Mieux-être", 1, 0));
        produits.add(new Produit(81, "Carrés de chocolat mi-sucré pour cuisson", 1, 0));
        produits.add(new Produit(82, "Barre de chocolat, Mars", 1, 0));
        produits.add(new Produit(83, "Craquelins originals en bouchées, Breton", 1, 0));
        produits.add(new Produit(84, "Biscuits à la guimauve enrobés de chocolat forêt noire, Whippet", 1, 0));
        produits.add(new Produit(85, "Compotes aux pommes, pêches et mangues sans sucre ajouté, Mieux-être", 1, 0));
        produits.add(new Produit(86, "Tablette de chocolat noir à la fleur de sel, Excellence", 1, 0));
        produits.add(new Produit(87, "Gateaux doigts de dame à la gelée", 1, 0));
        produits.add(new Produit(88, "Craquelins à saveur de fromage suisse", 1, 0));
        produits.add(new Produit(89, "Maïs à éclater Gourmet™ au goût de extra beurre, Bol à Éclater", 1, 0));
        produits.add(new Produit(90, "Pépites de chocolat noir, Chipits", 1, 0));
        produits.add(new Produit(91, "Biscuits petit beurre, Traditions", 1, 0));
        produits.add(new Produit(92, "Croustilles cornichons à l'aneth format familial", 1, 0));
        produits.add(new Produit(93, "Mini biscuits-sandwichs, Oreo", 1, 0));
        produits.add(new Produit(94, "Biscuits gaufrettes à la vanille enrobés de chocolat au lait, Célébration", 1, 0));
        produits.add(new Produit(95, "Compote de pomme originale, Fruitsations", 1, 0));
        produits.add(new Produit(96, "Croustilles sel marin et poivre format familial", 1, 0));
        produits.add(new Produit(101, "Croustilles à l'ancienne au piment jalapeño", 1, 0));
        produits.add(new Produit(102, "Moules au chocolat et beurre d'arachide, Reese", 1, 0));
        produits.add(new Produit(103, "Assortiment de craquelins", 1, 0));
        produits.add(new Produit(104, "Gaufrettes de grains entiers, P'tite Abeille", 1, 0));
        produits.add(new Produit(105, "Biscuits soda saupoudrés de sel", 1, 0));
        produits.add(new Produit(106, "Croustilles lime et poivre noir", 1, 0));
        produits.add(new Produit(107, "Pâtisseries feuilletées aux trois fruits, Passion Flakie", 1, 0));
        produits.add(new Produit(108, "Croustilles bacon fumé format familial", 1, 0));
        produits.add(new Produit(109, "Croustilles aneth crémeux", 1, 0));
        produits.add(new Produit(110, "Croustilles classiques format party", 1, 0));
        produits.add(new Produit(111, "Craquelins de riz nature, Mieux-être", 1, 0));
        produits.add(new Produit(112, "Coupes de pouding caramel au beurre", 1, 0));
        produits.add(new Produit(113, "Coupes de salade de fruits dans l'eau avec plus de cerises et sans sucre ajouté", 1, 0));
        produits.add(new Produit(114, "Barre de chocolat, Crunchie", 1, 0));
        produits.add(new Produit(115, "Barre de chocolat, Mr. Big", 1, 0));
        produits.add(new Produit(116, "Tablette de chocolat noir à saveur de caramel et sel de mer, Excellence", 1, 0));
        produits.add(new Produit(121, "Croustilles à l'ancienne 3 fromages et oignon rôti", 1, 0));
        produits.add(new Produit(122, "Craquelins au basilic et huile d'olive, Breton", 1, 0));
        produits.add(new Produit(123, "Collation mélange fiesta", 1, 0));
        produits.add(new Produit(124, "Biscuits aux brisures de chocolat belge et morceaux de chocolat au lait, Choco", 1, 0));
        produits.add(new Produit(125, "Fondant au soja au chocolat noir", 1, 0));
        produits.add(new Produit(126, "Biscuits petit beurre en sachets individuels, Tradition", 1, 0));
        produits.add(new Produit(127, "Biscuits au beurre garnis de chocolat noir à 45 % de cacao, Célébration", 1, 0));
        produits.add(new Produit(128, "Croustilles multigrains cheddar de campagne", 1, 0));
        produits.add(new Produit(129, "Croustilles BBQ", 1, 0));
        produits.add(new Produit(130, "Craquelins cuits au four à saveur de trio de fromages, Goldfish", 1, 0));
        produits.add(new Produit(131, "Salade de fruits en coupes dans du jus avec beaucoup de cerises", 1, 0));
        produits.add(new Produit(132, "Biscuits feuille d'érable, Tradition", 1, 0));
        produits.add(new Produit(133, "Barres goût original, Carrés aux Rice Krispies", 1, 0));
        produits.add(new Produit(134, "Maïs éclaté", 1, 0));
        produits.add(new Produit(135, "Chips tortilla au BBQ éclaté", 1, 0));
        produits.add(new Produit(136, "Croustilles à saveur de crème sure et oignon", 1, 0));
        produits.add(new Produit(141, "Pistaches rôties et salées", 1, 0));
        produits.add(new Produit(142, "Gobelets pour crème glacée", 1, 0));
        produits.add(new Produit(143, "Biscuits originaux, FudgeeO", 1, 0));
        produits.add(new Produit(144, "Maïs à éclater Gourmet™ au goût de beurre, Bol à Éclater", 1, 0));
        produits.add(new Produit(145, "Canneberges séchées et sucrées", 1, 0));
        produits.add(new Produit(146, "Croustilles de riz aux légumes à saveur de fines herbes italiennes et huile d'olive, Crispy Minis", 1, 0));
        produits.add(new Produit(147, "Croustilles nature format party", 1, 0));
        produits.add(new Produit(148, "Croustilles de riz aux légumes à saveur de vinaigre balsamique et bruschetta, Crispy Minis", 1, 0));
        produits.add(new Produit(149, "Compote de pommes et poires originale, Fruitsations", 1, 0));
        produits.add(new Produit(150, "Croustilles de riz à saveur de maïs soufflé au beurre, Crispy Minis", 1, 0));
        produits.add(new Produit(151, "Barres tendres au caramel enrobées de chocolat, Chocomax", 1, 0));
        produits.add(new Produit(152, "Bâtonnets biscuits à enrobage chocolaté, Normandie", 1, 0));
        produits.add(new Produit(153, "Biscuits au chocolat blanc et noix de macadamia", 1, 0));
        produits.add(new Produit(154, "Pouding au riz original sans gluten", 1, 0));
        produits.add(new Produit(155, "Barres tendres aux brisures de chocolat enrobées de chocolat au lait, Dipps", 1, 0));
        produits.add(new Produit(156, "Mini biscuits en sachets, Chips Ahoy!", 1, 0));
        produits.add(new Produit(161, "Croustilles originales cuites en marmite allégées en gras", 1, 0));
        produits.add(new Produit(162, "Croustilles à l'ancienne olive et féta", 1, 0));
        produits.add(new Produit(163, "Mélange à gâteau blanc, Super Moist", 1, 0));
        produits.add(new Produit(164, "Dés de pêches en coupe dans du jus de fruit", 1, 0));
        produits.add(new Produit(165, "Gobelets pour crème glacée", 1, 0));
        produits.add(new Produit(166, "Craquelins ronds natures, Melba Canapé", 1, 0));
        produits.add(new Produit(167, "Chips tortilla au piment infernal", 1, 0));
        produits.add(new Produit(168, "Friandise chocolatée, Cherry Blossom", 1, 0));
        produits.add(new Produit(169, "Grains de chocolat blanc pur, Chipits", 1, 0));
        produits.add(new Produit(170, "Compote de pommes non sucrée, Mieux-être", 1, 0));
        produits.add(new Produit(171, "Biscuits thé social, Traditions", 1, 0));
        produits.add(new Produit(172, "Biscuits aux morceaux et brisures de chocolat noir 70 % cacao, Choco", 1, 0));
        produits.add(new Produit(173, "Croustilles de riz à saveur de ketchup, Crispy Minis", 1, 0));
        produits.add(new Produit(174, "Croustilles originales cuites en marmite", 1, 0));
        produits.add(new Produit(175, "Biscuits thé social dans des sachets individuels, Tradition", 1, 0));
        produits.add(new Produit(176, "Croustilles à l'ancienne barbecue épicé, Coupe Épaisse", 1, 0));

        return produits;
    }
    static Produits creeListeProduitBoisson() {
        Produits produits = new Produits();
        produits.add(new Produit(1, "Jus d'orange sans pulpe, Pure Premium", 1, 0));
        produits.add(new Produit(2, "Eau de source naturelle", 1, 0));
        produits.add(new Produit(3, "Jus d'orange avec un peu de pulpe Homestyle, Pure premium", 1, 0));
        produits.add(new Produit(4, "Jus d'orange sans pulpe", 1, 0));
        produits.add(new Produit(5, "Jus de tomate", 1, 0));
        produits.add(new Produit(6, "Boisson gazeuse", 1, 0));
        produits.add(new Produit(7, "Cocktail aux légumes original", 1, 0));
        produits.add(new Produit(8, "Jus d'orange pur à 100 % sans pulpe", 1, 0));
        produits.add(new Produit(9, "Jus d'orange Pur déjeuner™ avec vitamine C ajoutée, Classique", 1, 0));
        produits.add(new Produit(10, "Cocktail aux légumes original, Garden Cocktail", 1, 0));
        produits.add(new Produit(11, "Jus de pomme, Classique", 1, 0));
        produits.add(new Produit(12, "Jus d'orange avec pulpe", 1, 0));
        produits.add(new Produit(13, "Jus d'orange pur à 100 % avec pulpe", 1, 0));
        produits.add(new Produit(14, "Cocktail de tomate et de palourdes L'Original, Clamato", 1, 0));
        produits.add(new Produit(15, "Jus de pomme et raisin, Classique", 1, 0));
        produits.add(new Produit(16, "Boisson gazeuse", 1, 0));
        produits.add(new Produit(21, "Jus d'orange sans pulpe", 1, 0));
        produits.add(new Produit(22, "Bière légère de type Lager", 1, 0));
        produits.add(new Produit(23, "Eau de source naturelle gazéifiée", 1, 0));
        produits.add(new Produit(24, "Jus d'orange avec beaucoup de pulpe Grovestand®, Pure Premium", 1, 0));
        produits.add(new Produit(25, "Vin blanc d'Italie, Splendido", 1, 0));
        produits.add(new Produit(26, "Jus de tomate en conserve", 1, 0));
        produits.add(new Produit(27, "Lait de coco de qualité supérieure", 1, 0));
        produits.add(new Produit(28, "Jus de pomme et raisin, Classique", 1, 0));
        produits.add(new Produit(29, "Jus de pomme, Classique", 1, 0));
        produits.add(new Produit(30, "Eau minérale naturelle gazéifiée", 1, 0));
        produits.add(new Produit(31, "Eau de source naturelle gazéifiée avec arôme naturel de citron", 1, 0));
        produits.add(new Produit(32, "Jus de tomate", 1, 0));
        produits.add(new Produit(33, "Bière légère de type Lager", 1, 0));
        produits.add(new Produit(34, "Boisson gazeuse", 1, 0));
        produits.add(new Produit(35, "Jus aux fruits des champs, Classique", 1, 0));
        produits.add(new Produit(36, "Soda gingembre", 1, 0));
        produits.add(new Produit(41, "Limonade", 1, 0));
        produits.add(new Produit(42, "Lait de coco léger de qualité supérieure", 1, 0));
        produits.add(new Produit(43, "Cocktail aux légumes original, Garden Cocktail", 1, 0));
        produits.add(new Produit(44, "Boisson gazeuse", 1, 0));
        produits.add(new Produit(45, "Jus d'orange avec pulpe", 1, 0));
        produits.add(new Produit(46, "Jus d'orange sans pulpe, Pure Premium", 1, 0));
        produits.add(new Produit(47, "Eau de source naturelle", 1, 0));
        produits.add(new Produit(48, "Boisson gazeuse", 1, 0));
        produits.add(new Produit(49, "Jus de pomme, Classique", 1, 0));
        produits.add(new Produit(50, "Eau minérale naturelle gazéifiée", 1, 0));
        produits.add(new Produit(51, "Bière blonde de type Lager", 1, 0));
        produits.add(new Produit(52, "Jus de pomme, 70 Calories", 1, 0));
        produits.add(new Produit(53, "Cocktail aux légumes à faible teneur en sodium", 1, 0));
        produits.add(new Produit(54, "Eau de source naturelle", 1, 0));
        produits.add(new Produit(55, "Boisson à saveur de punch aux fruits", 1, 0));
        produits.add(new Produit(56, "Eau de source naturelle gazéifiée avec arômes naturels de lime et de citron", 1, 0));
        produits.add(new Produit(61, "Soda gingembre", 1, 0));
        produits.add(new Produit(62, "Jus à saveur de Mangue exotique, Classique", 1, 0));
        produits.add(new Produit(63, "Boisson à saveur de pêche", 1, 0));
        produits.add(new Produit(64, "Vin rouge d'Italie, Glissando", 1, 0));
        produits.add(new Produit(65, "Jus de pomme fraîchement pressé", 1, 0));
        produits.add(new Produit(66, "Mélange de jus d'orange, de framboise et de fruit de la passion, Collection Nature", 1, 0));
        produits.add(new Produit(67, "Bière légère de type Lager", 1, 0));
        produits.add(new Produit(68, "Boisson à saveur de raisin", 1, 0));
        produits.add(new Produit(69, "Mélange de jus d'orange et de mangue, Collection Nature", 1, 0));
        produits.add(new Produit(70, "Café moulu torréfaction riche et corsée", 1, 0));
        produits.add(new Produit(71, "Jus de pomme avec vitamine C ajoutée fait de concentré", 1, 0));
        produits.add(new Produit(72, "Vin rouge d'Australie", 1, 0));
        produits.add(new Produit(73, "Boisson gazeuse diète", 1, 0));
        produits.add(new Produit(74, "Jus de pomme fait de concentré", 1, 0));
        produits.add(new Produit(75, "Jus d'orange Pur déjeuner™, Classique", 1, 0));
        produits.add(new Produit(76, "Eau déminéralisée", 1, 0));
        produits.add(new Produit(81, "Vin rouge d'Italie, Vivere", 1, 0));
        produits.add(new Produit(82, "Cocktail aux légumes", 1, 0));
        produits.add(new Produit(83, "Breuvage de jus de fruits melon d'eau et pomme, Hydrafruit", 1, 0));
        produits.add(new Produit(84, "Eau gazéifiée pétillante à saveur d'orange, Pure Life", 1, 0));
        produits.add(new Produit(85, "Eau de source gazéifiée", 1, 0));
        produits.add(new Produit(86, "Boisson gazeuse diète", 1, 0));
        produits.add(new Produit(87, "Jus de pomme et raisin fait de concentré", 1, 0));
        produits.add(new Produit(88, "Eau de source naturelle gazéifiée", 1, 0));
        produits.add(new Produit(89, "Vin blanc d'Australie", 1, 0));
        produits.add(new Produit(90, "Boisson aux amandes enrichie non sucrée, Almond SoFresh", 1, 0));
        produits.add(new Produit(91, "Mélange de jus de fruits du verger, Collection Nature", 1, 0));
        produits.add(new Produit(92, "Boisson aux amandes enrichie non sucrée", 1, 0));
        produits.add(new Produit(93, "Boisson de soya biologique enrichie à la saveur de chocolat", 1, 0));
        produits.add(new Produit(94, "Eau de source naturelle gazéifiée avec arôme naturel de pamplemousse rose", 1, 0));
        produits.add(new Produit(95, "Jus d'orange, pêche et mangue", 1, 0));
        produits.add(new Produit(96, "Eau de source naturelle ozonée", 1, 0));
        produits.add(new Produit(101, "Boisson de soya biologique fortifiée à la saveur de chocolat", 1, 0));
        produits.add(new Produit(102, "Bière légère de type Lager", 1, 0));
        produits.add(new Produit(103, "Boisson gazeuse à saveur de citron-lime", 1, 0));
        produits.add(new Produit(104, "Jus d'ananas et orange exotique, 70 Calories", 1, 0));
        produits.add(new Produit(105, "Mélange de jus d'orange sanguine, de canneberge et de grenade, Collection Nature", 1, 0));
        produits.add(new Produit(106, "Vin blanc des États-Unis", 1, 0));
        produits.add(new Produit(107, "Jus de fruit Passion tropicale™, Classique", 1, 0));
        produits.add(new Produit(108, "Filtres à café genre panier", 1, 0));
        produits.add(new Produit(109, "Eau de source gazéifiée à saveur de citron", 1, 0));
        produits.add(new Produit(110, "Boisson aux amandes enrichie", 1, 0));
        produits.add(new Produit(111, "Jus d'orange avec un peu de pulpe Homestyle, Pure Premium", 1, 0));
        produits.add(new Produit(112, "Boisson gazeuse diète", 1, 0));
        produits.add(new Produit(113, "Boisson gazeuse sans calories", 1, 0));
        produits.add(new Produit(114, "Cocktail aux canneberges", 1, 0));
        produits.add(new Produit(115, "Jus de tomate", 1, 0));
        produits.add(new Produit(116, "Vin rosé d'Italie, Merlot Rosé", 1, 0));
        produits.add(new Produit(121, "Eau de source gazéifiée", 1, 0));
        produits.add(new Produit(122, "Breuvage de jus de fruits Fusion de fruits™, Hydrafruit", 1, 0));
        produits.add(new Produit(123, "Soda gingembre", 1, 0));
        produits.add(new Produit(124, "Café moulu mélange original", 1, 0));
        produits.add(new Produit(125, "Boisson gazeuse", 1, 0));
        produits.add(new Produit(126, "Bière blonde légère", 1, 0));
        produits.add(new Produit(127, "Café moulu mélange original", 1, 0));
        produits.add(new Produit(128, "Eau de source naturelle gazéifiée à saveur de citron et orange", 1, 0));
        produits.add(new Produit(129, "Jus d'orange et tangerine, Créations d'orange", 1, 0));
        produits.add(new Produit(130, "Jus de baies et grenade Antioxia™, Pause Santé", 1, 0));
        produits.add(new Produit(131, "Bière belge blonde de type Lager", 1, 0));
        produits.add(new Produit(132, "Jus d'orange et pamplemousse, Créations d'orange", 1, 0));
        produits.add(new Produit(133, "Jus de pomme et raisin fait de concentré", 1, 0));
        produits.add(new Produit(134, "Jus de pamplemousse Ruby Red, Pure Premium", 1, 0));
        produits.add(new Produit(135, "Boisson aux vrais fruits Amitiés fraises et fruits de la passion", 1, 0));
        produits.add(new Produit(136, "Boisson gazeuse à saveur d'orange", 1, 0));
        produits.add(new Produit(141, "Breuvage de jus à saveur de fusion de fruits, Hydrafruit", 1, 0));
        produits.add(new Produit(142, "Boisson passion pêche agrumes", 1, 0));
        produits.add(new Produit(143, "Eau de source gazéifiée à saveur de lime", 1, 0));
        produits.add(new Produit(144, "Boisson aux vrais fruits Symbiose aux fruits™", 1, 0));
        produits.add(new Produit(145, "Dosettes K-Cup® de café Mélange de la Maison, Keurig Hot", 1, 0));
        produits.add(new Produit(146, "Boisson gazeuse à saveur d'orange", 1, 0));
        produits.add(new Produit(147, "Jus à saveur de raisin Concord, framboise et grenade Antioxia™, Pause Santé", 1, 0));
        produits.add(new Produit(148, "Jus de pomme fraîchement pressé", 1, 0));
        produits.add(new Produit(149, "Jus de tomate avec 50 % moins de sel", 1, 0));
        produits.add(new Produit(150, "Jus d'orange sans pulpe, Pure Premium", 1, 0));
        produits.add(new Produit(151, "Boisson désaltérante à saveur Bleu cool™", 1, 0));
        produits.add(new Produit(152, "Vin blanc du Chili", 1, 0));
        produits.add(new Produit(153, "Soda tonique", 1, 0));
        produits.add(new Produit(154, "Boisson gazeuse, Cola", 1, 0));
        produits.add(new Produit(155, "Jus Pur déjeuner™, Classique", 1, 0));
        produits.add(new Produit(156, "Cocktail de tomate et de palourdes extra épicé, Clamato", 1, 0));
        produits.add(new Produit(161, "Boisson gazeuse", 1, 0));
        produits.add(new Produit(162, "Café instantané classique, Taster's Choice", 1, 0));
        produits.add(new Produit(163, "Café moulu Traditionnel", 1, 0));
        produits.add(new Produit(164, "Jus de grenade, mûre et framboise", 1, 0));
        produits.add(new Produit(165, "Cocktail de tomate et de palourdes L'Original, Clamato", 1, 0));
        produits.add(new Produit(166, "Bière hollandaise de type Lager", 1, 0));
        produits.add(new Produit(167, "Boisson aux agrumes", 1, 0));
        produits.add(new Produit(168, "Vin blanc d'Australie", 1, 0));
        produits.add(new Produit(169, "Boisson aux amandes enrichie à la vanille, Almond SoFresh", 1, 0));
        produits.add(new Produit(170, "Jus de pêche et clémentine, FruitZoo", 1, 0));
        produits.add(new Produit(171, "Vin blanc sec du Canada", 1, 0));
        produits.add(new Produit(172, "Cocktail aux canneberges", 1, 0));
        produits.add(new Produit(173, "Jus de légumes à faible teneur en sodium, Garden Cocktail", 1, 0));
        produits.add(new Produit(174, "Jus d'orange et mangue, Créations d'orange", 1, 0));
        produits.add(new Produit(175, "Soda tonique", 1, 0));
        produits.add(new Produit(176, "Cocktail de tomate et de palourdes L'Original, Clamato", 1, 0));

        return produits;
    }
    static Produits creeListeProduitBoulangerie() {
        Produits produits = new Produits();
        produits.add(new Produit(1, "Baguette", 1, 0));
        produits.add(new Produit(2, "Croissants au beurre", 1, 0));
        produits.add(new Produit(3, "Pain blanc tranché Ultra-moelleux™", 1, 0));
        produits.add(new Produit(4, "Pains à hot dog tranchés", 1, 0));
        produits.add(new Produit(5, "Pains à hamburgers tranchés", 1, 0));
        produits.add(new Produit(6, "Baguette", 1, 0));
        produits.add(new Produit(7, "Pains à hamburger Ultra-moelleux™", 1, 0));
        produits.add(new Produit(8, "Pains à hot-dog Ultra-moelleux™", 1, 0));
        produits.add(new Produit(9, "Pain blanc tranché ultra-moelleux", 1, 0));
        produits.add(new Produit(10, "Pain aux raisins marbré à la cannelle", 1, 0));
        produits.add(new Produit(11, "Pain français", 1, 0));
        produits.add(new Produit(12, "Pains panini blancs", 1, 0));
        produits.add(new Produit(13, "Pain blanc enrichi pour club sandwich, Moelleux", 1, 0));
        produits.add(new Produit(14, "Pain belge", 1, 0));
        produits.add(new Produit(15, "Pains à hamburger au sésame Ultra-moelleux™", 1, 0));
        produits.add(new Produit(16, "Pain blanc style italien tranché épais", 1, 0));
        produits.add(new Produit(21, "Pain italien", 1, 0));
        produits.add(new Produit(22, "Pains à hamburger avec graines de sésame", 1, 0));
        produits.add(new Produit(23, "Muffins anglais nature", 1, 0));
        produits.add(new Produit(24, "Bagels aux graines de sésame", 1, 0));
        produits.add(new Produit(25, "Pain blanc original style italien tranché épais", 1, 0));
        produits.add(new Produit(26, "Baguette française", 1, 0));
        produits.add(new Produit(27, "Gâteaux May West™ à saveur originale", 1, 0));
        produits.add(new Produit(28, "Demi baguette ciabatta, Artisan", 1, 0));
        produits.add(new Produit(29, "Vol-au-vent prédécoupés", 1, 0));
        produits.add(new Produit(30, "Muffins anglais nature", 1, 0));
        produits.add(new Produit(31, "Pain style Grand-Mère™ tranché avec grains moulus d'autrefois", 1, 0));
        produits.add(new Produit(32, "Pain allongé tranché aux 9 grains", 1, 0));
        produits.add(new Produit(33, "Pain aux raisins et cannelle tranché", 1, 0));
        produits.add(new Produit(34, "Pain blanc tranché style italien avec graines de sésame", 1, 0));
        produits.add(new Produit(35, "Pains à hamburger style italien", 1, 0));
        produits.add(new Produit(36, "Bagels au sésame", 1, 0));
        produits.add(new Produit(41, "Pains crustini extra-moelleux, paquet de 8, Toscana", 1, 0));
        produits.add(new Produit(42, "Pain blanc tranché", 1, 0));
        produits.add(new Produit(43, "Pain quinoa", 1, 0));
        produits.add(new Produit(44, "Tortillas de 7 po à saveur originale", 1, 0));
        produits.add(new Produit(45, "Miche campagnard", 1, 0));
        produits.add(new Produit(46, "Pain de blé entier de style italien tranché épais", 1, 0));
        produits.add(new Produit(47, "Pain tranché aux 14 céréales", 1, 0));
        produits.add(new Produit(48, "Tortillas de 10 po", 1, 0));
        produits.add(new Produit(49, "Pain naan original", 1, 0));
        produits.add(new Produit(50, "Pain blanc tranché", 1, 0));
        produits.add(new Produit(51, "Pain tranché italien aux 9 grains entiers, Campagnolo", 1, 0));
        produits.add(new Produit(52, "Pain parisien", 1, 0));
        produits.add(new Produit(53, "Pain tranché aux multigrains, Campagnolo", 1, 0));
        produits.add(new Produit(54, "Pain tranché aux 9 grains entiers", 1, 0));
        produits.add(new Produit(55, "Bagels nature", 1, 0));
        produits.add(new Produit(56, "Pain chia avec lin moulu", 1, 0));
        produits.add(new Produit(61, "Pain blanc enrichi pour club sandwich, Moelleux", 1, 0));
        produits.add(new Produit(62, "Biscuits à l'avoine", 1, 0));
        produits.add(new Produit(63, "Pain blanc style italien tranché épais avec graines de sésame", 1, 0));
        produits.add(new Produit(64, "Pain tranché au seigle de style belge", 1, 0));
        produits.add(new Produit(65, "Bagels tranchés au sésame", 1, 0));
        produits.add(new Produit(66, "Pain tranché aux 6 céréales", 1, 0));
        produits.add(new Produit(67, "Pain blanc style italien", 1, 0));
        produits.add(new Produit(68, "Gâteau au chocolat surgelé, Deep'n Delicious", 1, 0));
        produits.add(new Produit(69, "Petits pains blancs à salade", 1, 0));
        produits.add(new Produit(70, "Pain de blé entier à 100 %", 1, 0));
        produits.add(new Produit(71, "Tortillas de blé entier de 7 po", 1, 0));
        produits.add(new Produit(72, "Pain tranché aux grains rustiques avec quinoa", 1, 0));
        produits.add(new Produit(73, "Pain tranché club de blé entier", 1, 0));
        produits.add(new Produit(74, "Pains naan ronds", 1, 0));
        produits.add(new Produit(75, "Pain blanc tranché avec supergrains et fibres, Smart", 1, 0));
        produits.add(new Produit(76, "Pain blanc de style italien tranché épais avec graines de sésame", 1, 0));
        produits.add(new Produit(81, "Pain tranché à 100 % blé entier, Campagnolo", 1, 0));
        produits.add(new Produit(82, "Gâteaux éponge billot à la gelée", 1, 0));
        produits.add(new Produit(83, "Miche d'antan blanche", 1, 0));
        produits.add(new Produit(84, "Muffins anglais au blé entier", 1, 0));
        produits.add(new Produit(85, "Biscuits au chocolat blanc et noix de macadame", 1, 0));
        produits.add(new Produit(86, "Pain belge tranché au blé germé", 1, 0));
        produits.add(new Produit(87, "Baguette ciabatta, Artisan", 1, 0));
        produits.add(new Produit(88, "Pain tranché au seigle de style belge", 1, 0));
        produits.add(new Produit(89, "Gâteau marbré surgelé, Deep'n Delicious", 1, 0));
        produits.add(new Produit(90, "Bagels à la cannelle et aux raisins secs", 1, 0));
        produits.add(new Produit(91, "Biscuits à l'avoine et raisins", 1, 0));
        produits.add(new Produit(92, "Pains à hot dog style italien", 1, 0));
        produits.add(new Produit(93, "Petits pains portugais", 1, 0));
        produits.add(new Produit(94, "Petit pain belge", 1, 0));
        produits.add(new Produit(95, "Pain blanc tranché", 1, 0));
        produits.add(new Produit(96, "Croissant Micro Croissant®", 1, 0));
        produits.add(new Produit(101, "Pain tranché biologique aux grains germés", 1, 0));
        produits.add(new Produit(102, "Pain tranché multigrains sans gras et sans sucres ajoutés", 1, 0));
        produits.add(new Produit(103, "Pain blanc tranché", 1, 0));
        produits.add(new Produit(104, "Baguette blanche partiellement cuite, Oven Fresh", 1, 0));
        produits.add(new Produit(105, "Bagels tranchés natures", 1, 0));
        produits.add(new Produit(106, "Pâtisseries feuilletées aux trois fruits, Passion Flakie", 1, 0));
        produits.add(new Produit(107, "Biscuits à l'avoine à l'érable et noix", 1, 0));
        produits.add(new Produit(108, "Baguette blanche partiellement cuite", 1, 0));
        produits.add(new Produit(109, "Tortillas souples grandes", 1, 0));
        produits.add(new Produit(110, "Tarte au sucre à l'ancienne", 1, 0));
        produits.add(new Produit(111, "Pain au blé entier Sandwich Club™, Moelleux", 1, 0));
        produits.add(new Produit(112, "Bagels tranchés aux 12 céréales", 1, 0));
        produits.add(new Produit(113, "Pain tranché aux 12 grains", 1, 0));
        produits.add(new Produit(114, "Pain pita de blé entier", 1, 0));
        produits.add(new Produit(115, "Pain de ménage blanc tranché, Moelleux", 1, 0));
        produits.add(new Produit(116, "Gâteau marianne", 1, 0));
        produits.add(new Produit(121, "Tarte au citron et meringue", 1, 0));
        produits.add(new Produit(122, "Tarte à croûte profonde aux pommes, Artisan", 1, 0));
        produits.add(new Produit(123, "Bouchées feuilletées aux pommes", 1, 0));
        produits.add(new Produit(124, "Pain blanc tranché avec grains entiers, Vitalité", 1, 0));
        produits.add(new Produit(125, "Pain de blé entier à 100 % tranché épais", 1, 0));
        produits.add(new Produit(126, "Demi baguette ciabatta aux olives, Artisan", 1, 0));
        produits.add(new Produit(127, "Petits pains originaux à saucisse", 1, 0));
        produits.add(new Produit(128, "Pain tranché aux 12 céréales", 1, 0));
        produits.add(new Produit(129, "Tortillas de 7 po de blé entier, New York New York", 1, 0));
        produits.add(new Produit(130, "Muffins au délice de baies", 1, 0));
        produits.add(new Produit(131, "Tarte aux pommes", 1, 0));
        produits.add(new Produit(132, "Pain tranché aux raisins, miel et noisettes au levain", 1, 0));
        produits.add(new Produit(133, "Pain belge à l'ancienne tranché", 1, 0));
        produits.add(new Produit(134, "Biscuits aux morceaux de chocolat", 1, 0));
        produits.add(new Produit(135, "Tarte aux pommes et caramel", 1, 0));
        produits.add(new Produit(136, "Muffins anglais nature", 1, 0));
        produits.add(new Produit(141, "Bouchées feuilletées aux framboises", 1, 0));
        produits.add(new Produit(142, "Tarte au sucre", 1, 0));
        produits.add(new Produit(143, "Chaussons aux pommes", 1, 0));
        produits.add(new Produit(144, "Muffins aux carottes", 1, 0));
        produits.add(new Produit(145, "Pain tranché aux 14 céréales, Vitalité", 1, 0));
        produits.add(new Produit(146, "Biscuits à l'avoine et aux raisins", 1, 0));
        produits.add(new Produit(147, "Pain blanc croûté tranché style français, Classique", 1, 0));
        produits.add(new Produit(148, "Danoises aux pommes et au caramel", 1, 0));
        produits.add(new Produit(149, "Pain de seigle tranché", 1, 0));
        produits.add(new Produit(150, "Miche tranché paysan multigrain", 1, 0));
        produits.add(new Produit(151, "Tarte aux pacanes", 1, 0));
        produits.add(new Produit(152, "Mini croissants au fromage", 1, 0));
        produits.add(new Produit(153, "Mini pains hamburger avec graines de sésame", 1, 0));
        produits.add(new Produit(154, "Muffins aux bleuets cultivés", 1, 0));
        produits.add(new Produit(155, "Pain naan à l'ail", 1, 0));
        produits.add(new Produit(156, "Petits pains kaiser au fromage", 1, 0));
        produits.add(new Produit(161, "Pain au seigle tranché", 1, 0));
        produits.add(new Produit(162, "Gâteau à la vanille surgelé, Deep'n Delicious", 1, 0));
        produits.add(new Produit(163, "Pains plats à hamburger", 1, 0));
        produits.add(new Produit(164, "Pains à sous-marin au fromage 9 po", 1, 0));
        produits.add(new Produit(165, "Pain tranché 100 % blé entier", 1, 0));
        produits.add(new Produit(166, "Pain blanc enrichi à sandwich, Moelleux", 1, 0));
        produits.add(new Produit(167, "Mini muffins aux carottes", 1, 0));
        produits.add(new Produit(168, "Palmiers sucrés", 1, 0));
        produits.add(new Produit(169, "Pain à sandwich de blé entier 100 % tranché", 1, 0));
        produits.add(new Produit(170, "Petits pains blancs tranchés", 1, 0));
        produits.add(new Produit(171, "Tarte aux pommes", 1, 0));
        produits.add(new Produit(172, "Pain belge à l'ancienne", 1, 0));
        produits.add(new Produit(173, "Gâteaux Cosmic Brownies™ avec pépites de chocolat", 1, 0));
        produits.add(new Produit(174, "Madeleines", 1, 0));
        produits.add(new Produit(175, "Tortillas nature", 1, 0));
        produits.add(new Produit(176, "Tortillas nature", 1, 0));

        return produits;
    }
    static Produits creeListeProduitLaitiers() {
        Produits produits = new Produits();
        produits.add(new Produit(1, "Œufs gros", 1, 0));
        produits.add(new Produit(2, "Beurre salé", 1, 0));
        produits.add(new Produit(3, "Lait 2 %, PurFiltre", 1, 0));
        produits.add(new Produit(4, "Beurre demi-salé", 1, 0));
        produits.add(new Produit(5, "Lait 2 %", 1, 0));
        produits.add(new Produit(6, "Beurre salé", 1, 0));
        produits.add(new Produit(7, "Œufs très gros", 1, 0));
        produits.add(new Produit(8, "Tranches de fromage fondu, Singles", 1, 0));
        produits.add(new Produit(9, "Lait 2 %", 1, 0));
        produits.add(new Produit(10, "Lait 2 %", 1, 0));
        produits.add(new Produit(11, "Lait 2 %", 1, 0));
        produits.add(new Produit(12, "Fromage mozzarella", 1, 0));
        produits.add(new Produit(13, "Lait au chocolat 1 %", 1, 0));
        produits.add(new Produit(14, "Crème à cuisson plus épaisse 15 %, Ultra'crème", 1, 0));
        produits.add(new Produit(15, "Crème à fouetter 35 %, Ultra'crème", 1, 0));
        produits.add(new Produit(16, "Margarine originale", 1, 0));
        produits.add(new Produit(21, "Œufs gros", 1, 0));
        produits.add(new Produit(22, "Fromage à la crème original en brique", 1, 0));
        produits.add(new Produit(23, "Fromage mozzarella râpé", 1, 0));
        produits.add(new Produit(24, "Crème sure 14 %", 1, 0));
        produits.add(new Produit(25, "Beurre à l'ail provençal", 1, 0));
        produits.add(new Produit(26, "Fromage cheddar très doux", 1, 0));
        produits.add(new Produit(27, "Crème champêtre 15 %, Ultra'crème", 1, 0));
        produits.add(new Produit(28, "Tranches de fromage fondu de type cheddar", 1, 0));
        produits.add(new Produit(29, "Fromage cheddar marbré doux", 1, 0));
        produits.add(new Produit(30, "Fromage cheddar marbré", 1, 0));
        produits.add(new Produit(31, "Lait 1 %", 1, 0));
        produits.add(new Produit(32, "Fromage mozzarella", 1, 0));
        produits.add(new Produit(33, "Lait 2 %", 1, 0));
        produits.add(new Produit(34, "Fromage Oka à pâte demi-ferme", 1, 0));
        produits.add(new Produit(35, "Fromage mozzarella", 1, 0));
        produits.add(new Produit(36, "Lait 1 %, PurFiltre", 1, 0));
        produits.add(new Produit(41, "Lait 3,25 %", 1, 0));
        produits.add(new Produit(42, "Crème à café 10 %", 1, 0));
        produits.add(new Produit(43, "Yogourt à boire aux saveurs de fraises et de bananes 2 %, Yop", 1, 0));
        produits.add(new Produit(44, "Assortiment de yogourt à la saveur de petits fruits 1,5 %", 1, 0));
        produits.add(new Produit(45, "Yogourt à boire à la saveur de framboises 2 %, Yop", 1, 0));
        produits.add(new Produit(46, "Margarine originale", 1, 0));
        produits.add(new Produit(47, "Tartinade traditionnelle", 1, 0));
        produits.add(new Produit(48, "Crème à café 10 %, Ultra'crème", 1, 0));
        produits.add(new Produit(49, "Bâtonnets au fromage mozzarella Zébrés™, Ficello", 1, 0));
        produits.add(new Produit(50, "Tranches épaisses de fromage fondu de type cheddar", 1, 0));
        produits.add(new Produit(51, "Crème champêtre 35 %, Ultra'crème", 1, 0));
        produits.add(new Produit(52, "Tartinade traditionnelle", 1, 0));
        produits.add(new Produit(53, "Lait 1 %", 1, 0));
        produits.add(new Produit(54, "Fromage brick", 1, 0));
        produits.add(new Produit(55, "Fromage cheddar marbré", 1, 0));
        produits.add(new Produit(56, "Crème à cuisson 15 %", 1, 0));
        produits.add(new Produit(61, "Yogourt probiotique nature 2 %, Classique", 1, 0));
        produits.add(new Produit(62, "Mélange de fromages râpés italiano", 1, 0));
        produits.add(new Produit(63, "Yogourt à boire à la saveur de pêches 2 %, Yop", 1, 0));
        produits.add(new Produit(64, "Lait 3,25 %", 1, 0));
        produits.add(new Produit(65, "Yogourt probiotique à la saveur de vanille 2,9%, Activia", 1, 0));
        produits.add(new Produit(66, "Fromage mozzarella", 1, 0));
        produits.add(new Produit(67, "Mélange de fromages râpés tex mex", 1, 0));
        produits.add(new Produit(68, "Fromage cheddar fort", 1, 0));
        produits.add(new Produit(69, "Yogourt à boire à la saveur de bleuets 2 %, Yop", 1, 0));
        produits.add(new Produit(70, "Lait sans lactose 2 %", 1, 0));
        produits.add(new Produit(71, "Yogourt à boire à la saveur de vanille 2 %, Yop", 1, 0));
        produits.add(new Produit(72, "Fromage cheddar blanc très doux", 1, 0));
        produits.add(new Produit(73, "Fromage mozzarella râpé", 1, 0));
        produits.add(new Produit(74, "Crème à fouetter 35 %", 1, 0));
        produits.add(new Produit(75, "Fromage cheddar mi-fort", 1, 0));
        produits.add(new Produit(76, "Crème sure 14 %", 1, 0));
        produits.add(new Produit(81, "Fromage cottage 2 %", 1, 0));
        produits.add(new Produit(82, "Lait 3,25 %", 1, 0));
        produits.add(new Produit(83, "Tranches de fromage fondu de type cheddar sans gras", 1, 0));
        produits.add(new Produit(84, "Assortiment de yogourt aux petits fruits, 0 %", 1, 0));
        produits.add(new Produit(85, "Fromage cheddar mi-fort", 1, 0));
        produits.add(new Produit(86, "Fromage feta léger en saumure", 1, 0));
        produits.add(new Produit(87, "Crème à cuisson 35 %", 1, 0));
        produits.add(new Produit(88, "Fromage mozzarella partiellement écrémé", 1, 0));
        produits.add(new Produit(89, "Yogourt à boire à la saveur de fruits tropicaux 2 %, Yop", 1, 0));
        produits.add(new Produit(90, "Fromage frais à saveur d'ail et fines herbes", 1, 0));
        produits.add(new Produit(91, "Fromage mozzarella partiellement écrémé râpé", 1, 0));
        produits.add(new Produit(92, "Crème sure 14 %", 1, 0));
        produits.add(new Produit(93, "Fromage suisse léger", 1, 0));
        produits.add(new Produit(94, "Fromage à la crème nature en brique", 1, 0));
        produits.add(new Produit(95, "Yogourt nature 0 %, Grec", 1, 0));
        produits.add(new Produit(96, "Margarine or", 1, 0));
        produits.add(new Produit(101, "Lait 2 %, PurFiltre", 1, 0));
        produits.add(new Produit(102, "Fromage cheddar marbré", 1, 0));
        produits.add(new Produit(103, "Yogourt probiotique à la saveur de vanille 2,9 %, Classique", 1, 0));
        produits.add(new Produit(104, "Tranches épaisses de fromages fondu, Velveeta", 1, 0));
        produits.add(new Produit(105, "Yogourt grec 2 % à saveur de framboise et grenade, Oikos", 1, 0));
        produits.add(new Produit(106, "Yogourt probiotique nature 0 %, Classique", 1, 0));
        produits.add(new Produit(107, "Yogourt probiotique à la saveur de framboises 2,9 %, Activia", 1, 0));
        produits.add(new Produit(108, "Assortiment de yogourts probiotiques aux fruits rouges 2,9 %, Activia", 1, 0));
        produits.add(new Produit(109, "Fromage fondu à tartiner", 1, 0));
        produits.add(new Produit(110, "Fromage mozzarella partiellement écrémé", 1, 0));
        produits.add(new Produit(111, "Bâtonnets au fromage mozzarella, Ficello", 1, 0));
        produits.add(new Produit(112, "Beurre à l'ail", 1, 0));
        produits.add(new Produit(113, "Assortiment de yogourts brassés Duo 1,5 %, Crémeux", 1, 0));
        produits.add(new Produit(114, "Fromage à la crème léger", 1, 0));
        produits.add(new Produit(115, "Yogourt nature 2 %, Grec", 1, 0));
        produits.add(new Produit(116, "Yogourt probiotique à la saveur de fraises 2,9 %, Activia", 1, 0));
        produits.add(new Produit(121, "Œufs gros", 1, 0));
        produits.add(new Produit(122, "Fromage cottage 2 %", 1, 0));
        produits.add(new Produit(123, "Yogourt probiotique à la saveur de cerises 2,9 %, Activia", 1, 0));
        produits.add(new Produit(124, "Assortiment de yogourt à boire à la saveur de fraises 1 %, Nano", 1, 0));
        produits.add(new Produit(125, "Fromages bocconcini cocktail", 1, 0));
        produits.add(new Produit(126, "Lait 1 %, PurFiltre", 1, 0));
        produits.add(new Produit(127, "Mélange de fromages râpés double cheddar", 1, 0));
        produits.add(new Produit(128, "Fromage frais épicé à l'échalote et ciboulette", 1, 0));
        produits.add(new Produit(129, "Fromage à pâte molle", 1, 0));
        produits.add(new Produit(130, "Lait au chocolat 1 %", 1, 0));
        produits.add(new Produit(131, "Fromage Oka à pâte demi-ferme Classique", 1, 0));
        produits.add(new Produit(132, "Fromage à la crème léger", 1, 0));
        produits.add(new Produit(133, "Assortiment de yogourts aux saveurs de baies et de pêches 0 %, Source", 1, 0));
        produits.add(new Produit(134, "Crème sure 14 %", 1, 0));
        produits.add(new Produit(135, "Fromage suisse tranché sans lactose", 1, 0));
        produits.add(new Produit(136, "Mélange de fromages râpés pizza", 1, 0));
        produits.add(new Produit(141, "Yogourt aux fraises 0 %, Grec", 1, 0));
        produits.add(new Produit(142, "Tranches de fromage fondu suisse, Singles", 1, 0));
        produits.add(new Produit(143, "Yogourt grec aux fraises 2 %, Oikos", 1, 0));
        produits.add(new Produit(144, "Yogourt grec à la lime 2 %, Oikos", 1, 0));
        produits.add(new Produit(145, "Crème champêtre 15 %, Ultra'crème", 1, 0));
        produits.add(new Produit(146, "Fromage mozzarella partiellement écrémé", 1, 0));
        produits.add(new Produit(147, "Yogourt à la saveur de vanille, 0 %", 1, 0));
        produits.add(new Produit(148, "Fromage cottage 2 %", 1, 0));
        produits.add(new Produit(149, "Fromage cheddar doux", 1, 0));
        produits.add(new Produit(150, "Assortiment de yogourt aux fruits d'été 2 %, Le Crémeux", 1, 0));
        produits.add(new Produit(151, "Fromage râpé mélange italiano", 1, 0));
        produits.add(new Produit(152, "Assortiment de yogourts brassés crémeux à saveur de baies et cerises 2 %", 1, 0));
        produits.add(new Produit(153, "Fromage cottage 1 %", 1, 0));
        produits.add(new Produit(154, "Fromage Oka à pâte ferme l'Artisan", 1, 0));
        produits.add(new Produit(155, "Fromage mozzarella râpé à pizza", 1, 0));
        produits.add(new Produit(156, "Fromage cheddar doux marbré léger", 1, 0));
        produits.add(new Produit(161, "Vinaigrette et trempette César", 1, 0));
        produits.add(new Produit(162, "Assortiment de yogourts brassés à la saveur de fruits 1,5 %, Crémeux", 1, 0));
        produits.add(new Produit(163, "Crème de table 15 %, Ultra'crème", 1, 0));
        produits.add(new Produit(164, "Fromage cheddar mi-fort", 1, 0));
        produits.add(new Produit(165, "Yogourt probiotique à la saveur de bleuets 2,9 %, Activia", 1, 0));
        produits.add(new Produit(166, "Yogourt à la saveur de vanille 0 %, Source", 1, 0));
        produits.add(new Produit(167, "Fromage à la crème original, Fouetté", 1, 0));
        produits.add(new Produit(168, "Fromage cheddar extra-fort", 1, 0));
        produits.add(new Produit(169, "Yogourt grec nature 0 %, Oikos", 1, 0));
        produits.add(new Produit(170, "Pâte à croissant à saveur originale", 1, 0));
        produits.add(new Produit(171, "Fromage cheddar mi-fort", 1, 0));
        produits.add(new Produit(172, "Yogourt probiotique à la saveur de vanille 0 %, Activia", 1, 0));
        produits.add(new Produit(173, "Assortiment de yogourt à la saveur de fruits tropicaux 1,5 %", 1, 0));
        produits.add(new Produit(174, "Crème à l'ancienne 15 %", 1, 0));
        produits.add(new Produit(175, "Yogourt grec à la vanille 2 %, Oikos", 1, 0));
        produits.add(new Produit(176, "Yogourt probiotique à la saveur de fraises 2,9 %, Classique", 1, 0));

        return produits;
    }
    static Produits creeListeProduitEpicerie() {
        Produits produits = new Produits();
        produits.add(new Produit(1, "Sucre granulé spécial fin", 1, 0));
        produits.add(new Produit(2, "Sirop d'érable foncé", 1, 0));
        produits.add(new Produit(3, "Ketchup aux tomates", 1, 0));
        produits.add(new Produit(4, "Mayonnaise", 1, 0));
        produits.add(new Produit(5, "Soupe aux tomates condensée", 1, 0));
        produits.add(new Produit(6, "Cassonade dorée", 1, 0));
        produits.add(new Produit(7, "Tomates en dés", 1, 0));
        produits.add(new Produit(8, "Macaroni et fromage original", 1, 0));
        produits.add(new Produit(9, "Bouillon original pour fondue et cuisson, Canton", 1, 0));
        produits.add(new Produit(10, "Moutarde jaune préparée, Classic Yellow", 1, 0));
        produits.add(new Produit(11, "Tomates en dés", 1, 0));
        produits.add(new Produit(12, "Tartinade aux noisettes avec lait écrémé et cacao", 1, 0));
        produits.add(new Produit(13, "Olives Manzanilla farcies avec pâte de piments", 1, 0));
        produits.add(new Produit(14, "Tomates en dés avec épices italiennes", 1, 0));
        produits.add(new Produit(15, "Salsa douce", 1, 0));
        produits.add(new Produit(16, "Ketchup aux tomates", 1, 0));
        produits.add(new Produit(21, "Sauce chili", 1, 0));
        produits.add(new Produit(22, "Relish verte sucrée", 1, 0));
        produits.add(new Produit(23, "Pâtes macaroni coupées", 1, 0));
        produits.add(new Produit(24, "Sauce soya, Chinoise", 1, 0));
        produits.add(new Produit(25, "Mélange à soupe poulet et nouilles", 1, 0));
        produits.add(new Produit(26, "Tomates en dés aux fines herbes et épices", 1, 0));
        produits.add(new Produit(27, "Pâtes spaghettini", 1, 0));
        produits.add(new Produit(28, "Soupe aux pois", 1, 0));
        produits.add(new Produit(29, "Mayonnaise", 1, 0));
        produits.add(new Produit(30, "Gruau rapide", 1, 0));
        produits.add(new Produit(31, "Sauce à sandwich hot chicken", 1, 0));
        produits.add(new Produit(32, "Tartinade de fromage", 1, 0));
        produits.add(new Produit(33, "Maïs en grains entiers", 1, 0));
        produits.add(new Produit(34, "Tomates en dés sans sel ajouté", 1, 0));
        produits.add(new Produit(35, "Pâte de tomates à faible teneur en sodium", 1, 0));
        produits.add(new Produit(36, "Bouillon de poulet sans sel ajouté, Mieux-être", 1, 0));
        produits.add(new Produit(41, "Soupe aux tomates condensée", 1, 0));
        produits.add(new Produit(42, "Huile de canola", 1, 0));
        produits.add(new Produit(43, "Pois de grosseurs assorties", 1, 0));
        produits.add(new Produit(44, "Vinaigre blanc", 1, 0));
        produits.add(new Produit(45, "Petits pois grosseurs 1 et 2", 1, 0));
        produits.add(new Produit(46, "Sauce à salade, Miracle Whip", 1, 0));
        produits.add(new Produit(47, "Pâtes à lasagne", 1, 0));
        produits.add(new Produit(48, "Bouillon de poulet prêt à utiliser avec 30 % moins de sodium", 1, 0));
        produits.add(new Produit(49, "Vermicelle de riz", 1, 0));
        produits.add(new Produit(50, "Farine blanche tout usage", 1, 0));
        produits.add(new Produit(51, "Mélasse de qualité fantaisie", 1, 0));
        produits.add(new Produit(52, "Pâtes spaghettini", 1, 0));
        produits.add(new Produit(53, "Tartinade aux noisettes avec lait écrémé et cacao", 1, 0));
        produits.add(new Produit(54, "Tomates en dés avec épices italiennes sans sel ajouté", 1, 0));
        produits.add(new Produit(55, "Pâtes macaroni coupées", 1, 0));
        produits.add(new Produit(56, "Pois chiches sans sel ajouté, Mieux-être", 1, 0));
        produits.add(new Produit(61, "Maïs en crème", 1, 0));
        produits.add(new Produit(62, "Soupe aux légumes du jardin", 1, 0));
        produits.add(new Produit(63, "Maïs en crème", 1, 0));
        produits.add(new Produit(64, "Macaroni en coudes", 1, 0));
        produits.add(new Produit(65, "Pâte de tomates aux fines herbes et épices", 1, 0));
        produits.add(new Produit(66, "Tortillas de 7 po à saveur originale", 1, 0));
        produits.add(new Produit(67, "Thon pâle listao en morceaux", 1, 0));
        produits.add(new Produit(68, "Cornichons sucrés marinés", 1, 0));
        produits.add(new Produit(69, "Fèves au goût de sirop d'érable", 1, 0));
        produits.add(new Produit(70, "Céréales granola recette originale, Croque Nature", 1, 0));
        produits.add(new Produit(71, "Spaghettini", 1, 0));
        produits.add(new Produit(72, "Maïs en grains entiers sans sel ajouté, Mieux-être", 1, 0));
        produits.add(new Produit(73, "Soupe aux tomates grand-mère condensée", 1, 0));
        produits.add(new Produit(74, "Spaghettini", 1, 0));
        produits.add(new Produit(75, "Farine tout usage originale", 1, 0));
        produits.add(new Produit(76, "Céréales, Corn Flakes", 1, 0));
        produits.add(new Produit(81, "Tomates broyées", 1, 0));
        produits.add(new Produit(82, "Dattes sans noyaux, Jaffa", 1, 0));
        produits.add(new Produit(83, "Pâtes spaghetti", 1, 0));
        produits.add(new Produit(84, "Riz basmati instantané, Bistro Express", 1, 0));
        produits.add(new Produit(85, "Pois de grosseurs assorties", 1, 0));
        produits.add(new Produit(86, "Lait de coco de qualité supérieure", 1, 0));
        produits.add(new Produit(87, "Bicarbonate de soude", 1, 0));
        produits.add(new Produit(88, "Trempette aux prunes, Chinoise", 1, 0));
        produits.add(new Produit(89, "Shortening, Tout Végétal", 1, 0));
        produits.add(new Produit(90, "Gruau instantané aux arômes érable et cassonade en sachets", 1, 0));
        produits.add(new Produit(91, "Vinaigre blanc", 1, 0));
        produits.add(new Produit(92, "Pâtes macaroni coupées", 1, 0));
        produits.add(new Produit(93, "Pâtes spaghettini", 1, 0));
        produits.add(new Produit(94, "Bouillon de poulet prêt à utiliser sans sel ajouté", 1, 0));
        produits.add(new Produit(95, "Pâtes farfalle", 1, 0));
        produits.add(new Produit(96, "Soupe aux tomates condensée avec 40% moins de sodium", 1, 0));
        produits.add(new Produit(101, "Tartinade au caramel", 1, 0));
        produits.add(new Produit(102, "Thon pâle en morceaux dans l'eau", 1, 0));
        produits.add(new Produit(103, "Sauce à la viande", 1, 0));
        produits.add(new Produit(104, "Sauce tomate aux oignons, fines herbes et épices", 1, 0));
        produits.add(new Produit(105, "Bouillon de poulet sans gras prêt à utiliser", 1, 0));
        produits.add(new Produit(106, "Maïs en grains entiers", 1, 0));
        produits.add(new Produit(107, "Ail haché", 1, 0));
        produits.add(new Produit(108, "Fécule de maïs", 1, 0));
        produits.add(new Produit(109, "Vinaigrette pour salade originale", 1, 0));
        produits.add(new Produit(110, "Huile d'olive extra vierge", 1, 0));
        produits.add(new Produit(111, "Ketchup aux tomates", 1, 0));
        produits.add(new Produit(112, "Maïs à grains entiers deux couleurs très sucré", 1, 0));
        produits.add(new Produit(113, "Riz pilaf cuit", 1, 0));
        produits.add(new Produit(114, "Mélange de six haricots sans sel ajouté, Mieux-être", 1, 0));
        produits.add(new Produit(115, "Moutarde jaune préparée", 1, 0));
        produits.add(new Produit(116, "Sauce barbecue originale", 1, 0));
        produits.add(new Produit(121, "Grains de chocolat pur mi-sucré, Chipits", 1, 0));
        produits.add(new Produit(122, "Bouchées de blé dorées et croustillantes avec un soupçon de miel, Sugar-Crisp", 1, 0));
        produits.add(new Produit(123, "Tomates en dés avec épices", 1, 0));
        produits.add(new Produit(124, "Tortillas de blé entier de 7 po", 1, 0));
        produits.add(new Produit(125, "Riz à grain long, Converted", 1, 0));
        produits.add(new Produit(126, "Huile de canola", 1, 0));
        produits.add(new Produit(127, "Pois verts tendres", 1, 0));
        produits.add(new Produit(128, "Mélange à sauce pour ragoût", 1, 0));
        produits.add(new Produit(129, "Salsa moyenne avec du vrai fromage, Salsa Con Queso", 1, 0));
        produits.add(new Produit(130, "Pâte de tomates à l'ail", 1, 0));
        produits.add(new Produit(131, "Cacao première qualité", 1, 0));
        produits.add(new Produit(132, "Pâtes spaghetti", 1, 0));
        produits.add(new Produit(133, "Pâte de tomates aux fines herbes et épices à faible teneur en sodium", 1, 0));
        produits.add(new Produit(134, "Cœurs de palmiers", 1, 0));
        produits.add(new Produit(135, "Sauce tomate originale", 1, 0));
        produits.add(new Produit(136, "Mélange pour soupe et recette à l'oignon", 1, 0));
        produits.add(new Produit(141, "Chapelure graham, P'tite Abeille", 1, 0));
        produits.add(new Produit(142, "Vraie mayonnaise", 1, 0));
        produits.add(new Produit(143, "Sauce à la viande", 1, 0));
        produits.add(new Produit(144, "Relish verte sucrée", 1, 0));
        produits.add(new Produit(145, "Pois et carottes", 1, 0));
        produits.add(new Produit(146, "Macédoine de légumes, Récoltés en saison", 1, 0));
        produits.add(new Produit(147, "Relish verte sucrée", 1, 0));
        produits.add(new Produit(148, "Beurre d'arachide léger crémeux", 1, 0));
        produits.add(new Produit(149, "Saindoux pur", 1, 0));
        produits.add(new Produit(150, "Mélange à gâteau saveur chocolat, Super Moist", 1, 0));
        produits.add(new Produit(151, "Morceaux et pieds de champignons", 1, 0));
        produits.add(new Produit(152, "Sauce brune", 1, 0));
        produits.add(new Produit(153, "Pâtes macaroni coupées", 1, 0));
        produits.add(new Produit(154, "Cœurs d'artichauts", 1, 0));
        produits.add(new Produit(155, "Céréales givrage original, Mini-Wheats", 1, 0));
        produits.add(new Produit(156, "Pois et carottes, Récoltés en saison", 1, 0));
        produits.add(new Produit(161, "Plat d'accompagnement de pâtes fettuccine Alfredo, Sidekicks", 1, 0));
        produits.add(new Produit(162, "Sauce chili goût maison avec morceaux de poivrons", 1, 0));
        produits.add(new Produit(163, "Pâtes boucles moyennes", 1, 0));
        produits.add(new Produit(164, "Pâtes penne rigate", 1, 0));
        produits.add(new Produit(165, "Riz à grains longs précuit enrichi", 1, 0));
        produits.add(new Produit(166, "Sauce soya avec 30% moins de sel", 1, 0));
        produits.add(new Produit(167, "Pâtes spaghettini", 1, 0));
        produits.add(new Produit(168, "Haricots rouge foncé", 1, 0));
        produits.add(new Produit(169, "Pâtes macaroni longues", 1, 0));
        produits.add(new Produit(170, "Sauce pour cuisson de côtes levées à l'ail medium, Chinoise", 1, 0));
        produits.add(new Produit(171, "Farine tout usage non blanchie", 1, 0));
        produits.add(new Produit(172, "Consommé de bœuf condensé", 1, 0));
        produits.add(new Produit(173, "Poudre à pâte", 1, 0));
        produits.add(new Produit(174, "Pâte de tomates à faible teneur en sodium", 1, 0));
        produits.add(new Produit(175, "Nouilles instantanées à saveur de poulet", 1, 0));
        produits.add(new Produit(176, "Mélange à soupe poulet et nouilles", 1, 0));

        return produits;

    }
    static Produits creeListeProduitViandeEtVolaille(){
        Produits produits = new Produits();
        produits.add(new Produit(1, "Rosbif de bas de palette désossé coupe européenne", 1, 0));
        produits.add(new Produit(2, "Veau de grain haché maigre", 1, 0));
        produits.add(new Produit(3, "Porc haché extra-maigre, format familial", 1, 0));
        produits.add(new Produit(4, "Brochettes de bœuf avec légumes", 1, 0));
        produits.add(new Produit(5, "Brochette de bœuf style kafta", 1, 0));
        produits.add(new Produit(6, "Rosettes de bœuf aux légumes, fromage et jambon", 1, 0));
        produits.add(new Produit(7, "Bœuf haché maigre, format familial", 1, 0));
        produits.add(new Produit(8, "Galette de bœuf haché maigre", 1, 0));
        produits.add(new Produit(9, "Bifteck d'aloyau", 1, 0));
        produits.add(new Produit(10, "Biftecks d'aloyau, format familial", 1, 0));
        produits.add(new Produit(11, "Bifteck de côtes", 1, 0));
        produits.add(new Produit(12, "Biftecks de côtes, format familial", 1, 0));
        produits.add(new Produit(13, "Bifteck de contre-filet", 1, 0));
        produits.add(new Produit(14, "Bifteck de faux-filet", 1, 0));
        produits.add(new Produit(15, "Biftecks de culotte de haut de surlonge, Angus", 1, 0));
        produits.add(new Produit(16, "Bavette de bœuf, Angus", 1, 0));
        produits.add(new Produit(21, "Cuisses de poulet sans dos, format familial", 1, 0));
        produits.add(new Produit(22, "Tournedos de poitrine de poulet", 1, 0));
        produits.add(new Produit(23, "Tournedos de poitrine de poulet assaisonés et enrobés de bacon surgelés", 1, 0));
        produits.add(new Produit(24, "Brochettes de filet de porc avec légumes", 1, 0));
        produits.add(new Produit(25, "Brochettes de médaillons de filet de porc bardés de bacon", 1, 0));
        produits.add(new Produit(26, "Brochette de porc style kafta", 1, 0));
        produits.add(new Produit(27, "Tournedos de porc bardés de bacon", 1, 0));
        produits.add(new Produit(28, "Filet de porc", 1, 0));
        produits.add(new Produit(29, "Tranches de surlonge de porc désossées, format familial", 1, 0));
        produits.add(new Produit(30, "Côtelettes de faux-filet de porc tranchées", 1, 0));
        produits.add(new Produit(31, "Côtelettes de porc BBQ désossées", 1, 0));
        produits.add(new Produit(32, "Côtelettes de porc coupe du centre, format familial", 1, 0));
        produits.add(new Produit(33, "Côtelettes de porc coupe du centre désossées, format familial", 1, 0));
        produits.add(new Produit(34, "Trio de côtelettes de porc", 1, 0));
        produits.add(new Produit(35, "Côtelettes de longe de porc coupe hôtel", 1, 0));
        produits.add(new Produit(36, "Côtelettes de porc papillon, format familial", 1, 0));
        produits.add(new Produit(41, "Filet de porc farci aux asperges et fromage", 1, 0));
        produits.add(new Produit(42, "Poitrine de poulet farcie aux épinards et au fromage", 1, 0));
        produits.add(new Produit(43, "Filet de porc farci au brie et canneberges", 1, 0));
        produits.add(new Produit(44, "Filet de porc farci au feta et à la bruschetta", 1, 0));
        produits.add(new Produit(45, "Saucisses italiennes douces", 1, 0));
        produits.add(new Produit(46, "Saucisses italiennes fortes", 1, 0));
        produits.add(new Produit(47, "Saucisses de chorizo", 1, 0));
        produits.add(new Produit(48, "Saucisses portugaises", 1, 0));
        produits.add(new Produit(49, "Saucisses de porc à la bière", 1, 0));
        produits.add(new Produit(50, "Saucisses au miel et à la moutarde", 1, 0));
        produits.add(new Produit(51, "Saucisses aux bleuets et à l'érable", 1, 0));
        produits.add(new Produit(52, "Saucisses aux pommes et oignons caramélisés", 1, 0));
        produits.add(new Produit(53, "Saucisses à la poutine", 1, 0));
        produits.add(new Produit(54, "Saucisses tacos", 1, 0));
        produits.add(new Produit(55, "Saucisses pizza", 1, 0));
        produits.add(new Produit(56, "Saucisses à l'orientale", 1, 0));
        produits.add(new Produit(61, "Burgers de surlonge de bœuf surgelés, La Boucherie", 1, 0));
        produits.add(new Produit(62, "Burgers de bœuf BBQ gigantesques surgelés, La Boucherie", 1, 0));
        produits.add(new Produit(63, "Burgers de bœuf gigantesques aux épices pour bifteck de Montréal surgelés, La Boucherie", 1, 0));
        produits.add(new Produit(64, "Burgers farcis au bacon et au cheddar surgelés", 1, 0));
        produits.add(new Produit(65, "Burgers farcis au fromage suisse et champignon portobello", 1, 0));
        produits.add(new Produit(66, "Burgers de kangourou surgelés", 1, 0));
        produits.add(new Produit(67, "Brochettes de poulet assaisonnées avec légumes", 1, 0));
        produits.add(new Produit(68, "Brochettes de poulet en marinade shish taouk", 1, 0));
        produits.add(new Produit(69, "Brochettes de médaillons de poulet bardés assaisonnés", 1, 0));
        produits.add(new Produit(70, "Poitrine de poulet en marinade shish taouk", 1, 0));
        produits.add(new Produit(71, "Poitrine de poulet en marinade souvlaki", 1, 0));
        produits.add(new Produit(72, "Poitrine de poulet assaisonnée, parée et désossée", 1, 0));
        produits.add(new Produit(73, "Souvlakis de poulet marinés", 1, 0));
        produits.add(new Produit(74, "Hauts de cuisse de poulet désossés en marinade shish taouk", 1, 0));
        produits.add(new Produit(75, "Hauts de cuisse de poulet désossés en marinade souvlaki", 1, 0));
        produits.add(new Produit(76, "Souvlakis de poulet assaisonnés", 1, 0));
        produits.add(new Produit(81, "Bifteck français shawarma", 1, 0));
        produits.add(new Produit(82, "Souvlakis de bœuf assaisonnés", 1, 0));
        produits.add(new Produit(83, "Souvlakis de bœuf marinés", 1, 0));
        produits.add(new Produit(84, "Biftecks de tournedos au poivre", 1, 0));
        produits.add(new Produit(85, "Brochettes de filet de porc avec légumes assaisonnées", 1, 0));
        produits.add(new Produit(86, "Brochettes de médaillons de filet de porc bardés de bacon assaisonnées", 1, 0));
        produits.add(new Produit(87, "Souvlakis de porc marinés", 1, 0));
        produits.add(new Produit(88, "Souvlakis de porc assaisonnés", 1, 0));
        produits.add(new Produit(89, "Côtelettes de porc BBQ désossées assaisonnées", 1, 0));
        produits.add(new Produit(90, "Côtelettes de porc coupe du centre désossées et assaisonnées", 1, 0));
        produits.add(new Produit(91, "Côtelettes de faux-filet de porc tranchées et assaisonnées", 1, 0));
        produits.add(new Produit(92, "Côtelette de porc coupe du centre assaisonnée", 1, 0));
        produits.add(new Produit(93, "Côtelettes de porc coupe hôtel assaisonnées", 1, 0));
        produits.add(new Produit(94, "Filet de porc en marinade souvlaki", 1, 0));
        produits.add(new Produit(95, "Filet de porc assaisonné", 1, 0));
        produits.add(new Produit(96, "Filet de porc en marinade shish taouk", 1, 0));
        produits.add(new Produit(101, "Bœuf haché mi-maigre, format familial", 1, 0));
        produits.add(new Produit(102, "Filets de porc, format familial", 1, 0));
        produits.add(new Produit(103, "Rosbif français d'intérieur de ronde non-bardé", 1, 0));
        produits.add(new Produit(104, "Bœuf pour fondue chinoise surgelé", 1, 0));
        produits.add(new Produit(105, "Cubes de bœuf bourguignon, format familial", 1, 0));
        produits.add(new Produit(106, "Rosbif de filet mignon", 1, 0));
        produits.add(new Produit(107, "Cuisses de poulet avec dos, format familial", 1, 0));
        produits.add(new Produit(108, "Rosbif de côtes croisées désossé", 1, 0));
        produits.add(new Produit(109, "Bifteck de filet mignon", 1, 0));
        produits.add(new Produit(110, "Mélange de bœuf et de porc hachés maigres, format familial", 1, 0));
        produits.add(new Produit(111, "Porc haché extra-maigre", 1, 0));
        produits.add(new Produit(112, "Saucisses fumées originales", 1, 0));
        produits.add(new Produit(113, "Boeuf pour fondue chinoise", 1, 0));
        produits.add(new Produit(114, "Bifteck français", 1, 0));
        produits.add(new Produit(115, "Poulet frais entier", 1, 0));
        produits.add(new Produit(116, "Bacon avec 50% moins de sel", 1, 0));
        produits.add(new Produit(121, "Poulets frais entiers de catégorie A, format familial", 1, 0));
        produits.add(new Produit(122, "Hauts de cuisse de poulet désossés et sans peau", 1, 0));
        produits.add(new Produit(123, "Viandes de bœuf, veau et porc hachées maigres", 1, 0));
        produits.add(new Produit(124, "Biftecks de tournedos non bardés, format familial", 1, 0));
        produits.add(new Produit(125, "Rôti de longe de porc coupe du centre désossée", 1, 0));
        produits.add(new Produit(126, "Côtes de dos de porc classiques cuites", 1, 0));
        produits.add(new Produit(127, "Veau de grain haché maigre, format familial", 1, 0));
        produits.add(new Produit(128, "Bacon à saveur d'érable", 1, 0));
        produits.add(new Produit(129, "Côtelettes de porc coupe du centre", 1, 0));
        produits.add(new Produit(130, "Poitrines de poulet avec dos, format familial", 1, 0));
        produits.add(new Produit(131, "Biftecks de tournedos non bardés", 1, 0));
        produits.add(new Produit(132, "Ailes de poulet Buffalo surgelées", 1, 0));
        produits.add(new Produit(133, "Jambon fumé Forêt-Noire extra maigre", 1, 0));
        produits.add(new Produit(134, "Bifteck au poivre", 1, 0));
        produits.add(new Produit(135, "Tranches de foie de veau de grain", 1, 0));
        produits.add(new Produit(136, "Cheval haché maigre", 1, 0));
        produits.add(new Produit(141, "Poitrine de poulet avec dos", 1, 0));
        produits.add(new Produit(142, "Bacon en tranches épaisses", 1, 0));
        produits.add(new Produit(143, "Demi-longe de porc bout de côtes désossée", 1, 0));
        produits.add(new Produit(144, "Poitrine de dindon désossée et sans peau", 1, 0));
        produits.add(new Produit(145, "Saucisses fumées au poulet", 1, 0));
        produits.add(new Produit(146, "Cubes de cuisse de boeuf pour fondue", 1, 0));
        produits.add(new Produit(147, "Pâté au poulet surgelé", 1, 0));
        produits.add(new Produit(148, "Pilons de poulet", 1, 0));
        produits.add(new Produit(149, "Rôti d'intérieur de ronde de bœuf", 1, 0));
        produits.add(new Produit(150, "Côtelettes de porc coupe du centre désossées, brunir et servir", 1, 0));
        produits.add(new Produit(151, "Bifteck de haut de surlonge désossé sans culotte", 1, 0));
        produits.add(new Produit(152, "Porc pour fondue chinoise surgelé", 1, 0));
        produits.add(new Produit(153, "Poulet entier", 1, 0));
        produits.add(new Produit(154, "Cuisses de poulet avec dos", 1, 0));
        produits.add(new Produit(155, "Duo de côtelettes de porc", 1, 0));
        produits.add(new Produit(156, "Bifteck d'intérieur de ronde à mariner", 1, 0));
        produits.add(new Produit(161, "Lanières de cuisse de bœuf", 1, 0));
        produits.add(new Produit(162, "Saucisses italienne douce", 1, 0));
        produits.add(new Produit(163, "Poulet de grain entier, Naturalia", 1, 0));
        produits.add(new Produit(164, "Cubes de bœuf désossés pour ragoût", 1, 0));
        produits.add(new Produit(165, "Ailes de poulet BBQ surgelées", 1, 0));
        produits.add(new Produit(166, "Saucisses au porc et au bœuf légères", 1, 0));
        produits.add(new Produit(167, "Lanières de poitrine de poulet", 1, 0));
        produits.add(new Produit(168, "Escalopes de poulet", 1, 0));
        produits.add(new Produit(169, "Poitrines de poulet désossées", 1, 0));
        produits.add(new Produit(170, "Osso bucco de porc", 1, 0));
        produits.add(new Produit(171, "Rôti de poire intérieur de ronde de bœuf", 1, 0));
        produits.add(new Produit(172, "Côtelettes de porc papillon", 1, 0));
        produits.add(new Produit(173, "Côtelettes de porc coupe du centre, brunir et servir", 1, 0));
        produits.add(new Produit(174, "Ailes de poulet paprika fumé et érable surgelées", 1, 0));
        produits.add(new Produit(175, "Filet mignon de bœuf entier", 1, 0));
        produits.add(new Produit(176, "Combo de saucisse italienne et allemande", 1, 0));

        return produits;
    }
    static Produits creeListeProduitFruitsEtLegumes(){
        Produits produits = new Produits();
        produits.add(new Produit(1, "Pomme, McIntosh", 1, 0));
        produits.add(new Produit(2, "Courge musquée", 1, 0));
        produits.add(new Produit(3, "Courge spaghetti", 1, 0));
        produits.add(new Produit(4, "Courge poivrée", 1, 0));
        produits.add(new Produit(5, "Courge buttercup", 1, 0));
        produits.add(new Produit(6, "Citrouille", 1, 0));
        produits.add(new Produit(7, "Courge delicata", 1, 0));
        produits.add(new Produit(8, "Courge Sweet Dumpling", 1, 0));
        produits.add(new Produit(9, "Banane", 1, 0));
        produits.add(new Produit(10, "Concombre anglais", 1, 0));
        produits.add(new Produit(11, "Champignons blancs", 1, 0));
        produits.add(new Produit(12, "Framboises", 1, 0));
        produits.add(new Produit(13, "Tomate rouge de serre", 1, 0));
        produits.add(new Produit(14, "Tomates rouges en grappe", 1, 0));
        produits.add(new Produit(15, "Carottes miniatures coupées", 1, 0));
        produits.add(new Produit(16, "Oignons verts", 1, 0));
        produits.add(new Produit(21, "Tomates raisins", 1, 0));
        produits.add(new Produit(22, "Carottes nantaises douces", 1, 0));
        produits.add(new Produit(23, "Banane biologique", 1, 0));
        produits.add(new Produit(24, "Cantaloup", 1, 0));
        produits.add(new Produit(25, "Chou vert", 1, 0));
        produits.add(new Produit(26, "Tomate rouge de serre", 1, 0));
        produits.add(new Produit(27, "Tomate rose de serre", 1, 0));
        produits.add(new Produit(28, "Pomme, Granny Smith", 1, 0));
        produits.add(new Produit(29, "Poivron vert", 1, 0));
        produits.add(new Produit(30, "Clémentine", 1, 0));
        produits.add(new Produit(31, "Ail", 1, 0));
        produits.add(new Produit(32, "Patate douce", 1, 0));
        produits.add(new Produit(33, "Laitue à feuilles vertes", 1, 0));
        produits.add(new Produit(34, "Jeunes épinards", 1, 0));
        produits.add(new Produit(35, "Oignon espagnol", 1, 0));
        produits.add(new Produit(36, "Quartier de melon d'eau sans pépins", 1, 0));
        produits.add(new Produit(41, "Mélange de salade printanier", 1, 0));
        produits.add(new Produit(42, "Laitue romaine", 1, 0));
        produits.add(new Produit(43, "Jeunes épinards", 1, 0));
        produits.add(new Produit(44, "Roquette", 1, 0));
        produits.add(new Produit(45, "Persil frisé", 1, 0));
        produits.add(new Produit(46, "Pomme de terre Russet", 1, 0));
        produits.add(new Produit(47, "Coriandre", 1, 0));
        produits.add(new Produit(48, "Ananas entier tranché", 1, 0));
        produits.add(new Produit(49, "Pommes de terre rouges", 1, 0));
        produits.add(new Produit(50, "Kiwi", 1, 0));
        produits.add(new Produit(51, "Sac d'épinards", 1, 0));
        produits.add(new Produit(52, "Laitue Boston vivante de serre en dôme", 1, 0));
        produits.add(new Produit(53, "Pommes de terre à chair jaune lavées", 1, 0));
        produits.add(new Produit(54, "Persil italien", 1, 0));
        produits.add(new Produit(55, "Pommes de terre russet", 1, 0));
        produits.add(new Produit(56, "Bleuets", 1, 0));
        produits.add(new Produit(61, "Basilic en emballage", 1, 0));
        produits.add(new Produit(62, "Mélange de salade San Marino", 1, 0));
        produits.add(new Produit(63, "Pomme jaune, Délicieuse", 1, 0));
        produits.add(new Produit(64, "Pois mange-tout", 1, 0));
        produits.add(new Produit(65, "Mélange de salade César avec garnitures", 1, 0));
        produits.add(new Produit(66, "Pommes de terre grelots fraîches, Terrific Trio", 1, 0));
        produits.add(new Produit(67, "Fenouil", 1, 0));
        produits.add(new Produit(68, "Pommes de terre grelots fraîches, Boomer Gold", 1, 0));
        produits.add(new Produit(69, "Ananas tropical gold", 1, 0));
        produits.add(new Produit(70, "Bouquet de ciboulette en emballage", 1, 0));
        produits.add(new Produit(71, "Courgette", 1, 0));
        produits.add(new Produit(72, "Petites pommes de terre à chair jaune lavées", 1, 0));
        produits.add(new Produit(73, "Oignon blanc", 1, 0));
        produits.add(new Produit(74, "Coriandre en emballage", 1, 0));
        produits.add(new Produit(75, "Basilic en pot", 1, 0));
        produits.add(new Produit(76, "Pommes de terre grelots fraîches, Blushing Belle", 1, 0));
        produits.add(new Produit(81, "Laitue à feuilles rouges", 1, 0));
        produits.add(new Produit(82, "Pomme, Honeycrisp", 1, 0));
        produits.add(new Produit(83, "Mélange de salade César avec garnitures", 1, 0));
        produits.add(new Produit(84, "Salade de fruits régulière", 1, 0));
        produits.add(new Produit(85, "Tofu pasteurisé régulier", 1, 0));
        produits.add(new Produit(86, "Tomates cerises", 1, 0));
        produits.add(new Produit(87, "Haricots verts", 1, 0));
        produits.add(new Produit(88, "Oignons rouges", 1, 0));
        produits.add(new Produit(89, "Pomme, Spartan", 1, 0));
        produits.add(new Produit(90, "Pomme grenade", 1, 0));
        produits.add(new Produit(91, "Mini melon d'eau sans pépins", 1, 0));
        produits.add(new Produit(92, "Pois sucrés", 1, 0));
        produits.add(new Produit(93, "Jeunes épinards biologiques", 1, 0));
        produits.add(new Produit(94, "Ail haché", 1, 0));
        produits.add(new Produit(95, "Feuilles de menthe en emballage", 1, 0));
        produits.add(new Produit(96, "Mélange de légumes coupés pour soupes", 1, 0));
        produits.add(new Produit(101, "Citron", 1, 0));
        produits.add(new Produit(102, "Poireaux tranchés et lavés", 1, 0));
        produits.add(new Produit(103, "Carottes biologiques", 1, 0));
        produits.add(new Produit(104, "Gros pamplemousse", 1, 0));
        produits.add(new Produit(105, "Thym en emballage", 1, 0));
        produits.add(new Produit(106, "Tartinade de tofu", 1, 0));
        produits.add(new Produit(107, "Chou rouge", 1, 0));
        produits.add(new Produit(108, "Mini poivrons doux", 1, 0));
        produits.add(new Produit(109, "Aneth en emballage", 1, 0));
        produits.add(new Produit(110, "Mélange bébé chou frisé", 1, 0));
        produits.add(new Produit(111, "Pommes de terre parisiennes", 1, 0));
        produits.add(new Produit(112, "Plateau de 4 légumes avec trempette ranch", 1, 0));
        produits.add(new Produit(113, "Mélange baie sublime", 1, 0));
        produits.add(new Produit(114, "Mélange de légumes coupés pour sauce à spaghetti", 1, 0));
        produits.add(new Produit(115, "Céleri biologique", 1, 0));
        produits.add(new Produit(116, "Poireau", 1, 0));
        produits.add(new Produit(121, "Piment jalapeno", 1, 0));
        produits.add(new Produit(122, "Salade mélange américain", 1, 0));
        produits.add(new Produit(123, "Tomates rouges en grappe biologiques", 1, 0));
        produits.add(new Produit(124, "Poire Rocha", 1, 0));
        produits.add(new Produit(125, "Tomate italienne", 1, 0));
        produits.add(new Produit(126, "Mélange de salade oriental", 1, 0));
        produits.add(new Produit(127, "Ail haché", 1, 0));
        produits.add(new Produit(128, "Mélange pour salade romaine classique", 1, 0));
        produits.add(new Produit(129, "Mélange pour salade César", 1, 0));
        produits.add(new Produit(130, "Sac de radis", 1, 0));
        produits.add(new Produit(131, "Canneberges séchées et sucrées", 1, 0));
        produits.add(new Produit(132, "Cantaloup en morceaux", 1, 0));
        produits.add(new Produit(133, "Cœurs de céleri", 1, 0));
        produits.add(new Produit(134, "Julienne de légumes", 1, 0));
        produits.add(new Produit(135, "Mangue rouge", 1, 0));
        produits.add(new Produit(136, "Couronne de brocoli enveloppée", 1, 0));
        produits.add(new Produit(141, "Mini tomates Kumato", 1, 0));
        produits.add(new Produit(142, "Pamplemousse", 1, 0));
        produits.add(new Produit(143, "Tofu extra ferme", 1, 0));
        produits.add(new Produit(144, "Pommes de terre grelots à l'ail et aux fines herbes avec kit à griller", 1, 0));
        produits.add(new Produit(145, "Champignons porteenies", 1, 0));
        produits.add(new Produit(146, "Avocats biologiques", 1, 0));
        produits.add(new Produit(147, "Plateau de 5 légumes", 1, 0));
        produits.add(new Produit(148, "Cœurs de laitue romaine biologiques", 1, 0));
        produits.add(new Produit(149, "Noix de Grenoble crues", 1, 0));
        produits.add(new Produit(150, "Plateau de fruits Le farouche", 1, 0));
        produits.add(new Produit(151, "Mélange de salade Grecque avec garnitures", 1, 0));
        produits.add(new Produit(152, "Plateau de mélange de crudités avec trempette ranch", 1, 0));
        produits.add(new Produit(153, "Plateau de fruits", 1, 0));
        produits.add(new Produit(154, "Betteraves", 1, 0));
        produits.add(new Produit(155, "Poivron rouge de champs", 1, 0));
        produits.add(new Produit(156, "Trio de pommes", 1, 0));
        produits.add(new Produit(161, "Sac de pommes, Gala", 1, 0));
        produits.add(new Produit(162, "Tofu mou", 1, 0));
        produits.add(new Produit(163, "Pommes de terre grelots fraîches à l'ail et au persil", 1, 0));
        produits.add(new Produit(164, "Dattes séchées dénoyautées", 1, 0));
        produits.add(new Produit(165, "Aubergine", 1, 0));
        produits.add(new Produit(166, "Sac de limes", 1, 0));
        produits.add(new Produit(167, "Salade de fruits régulière", 1, 0));
        produits.add(new Produit(168, "Plateau de fruits avec trempette au chocolat", 1, 0));
        produits.add(new Produit(169, "Tomates raisins orange", 1, 0));
        produits.add(new Produit(170, "Bébé bok choy", 1, 0));
        produits.add(new Produit(171, "Luzerne biologique", 1, 0));
        produits.add(new Produit(172, "Salade de fruits de luxe", 1, 0));
        produits.add(new Produit(173, "Raisins secs de Californie naturels", 1, 0));
        produits.add(new Produit(174, "Raisins secs de Californie naturels, Mini-Paquets", 1, 0));
        produits.add(new Produit(175, "Mélange de bébé romaine biologique", 1, 0));
        produits.add(new Produit(176, "Mangue miel", 1, 0));





        return produits;
    }
}
