package ca.qc.cgmatane.informatique.monmagasinage.donnees.base;

import ca.qc.cgmatane.informatique.monmagasinage.modele.Produit;
import ca.qc.cgmatane.informatique.monmagasinage.modele.pluriel.Produits;

import java.util.ArrayList;
import java.util.Arrays;

public interface RequeteInsertionProduit {
    final static ArrayList<Produits> tousMesProduits = new ArrayList<Produits>() {{
        add(creeListeProduitFruitsEtLegumes());
        add(creeListeProduitViandeEtVolaille());
    }};

    static Produits creeListeProduitViandeEtVolaille(){
        Produits produits = new Produits();
        produits.add(new Produit(1, "Rosbif de bas de palette désossé coupe européenne", 1, 0));
        produits.add(new Produit(2, "Veau de grain haché maigre", 1, 0));
        produits.add(new Produit(3, "Porc haché extra-maigre, format familial", 1, 0));
        produits.add(new Produit(4, "Brochettes de bœuf avec légumes", 1, 0));
        produits.add(new Produit(5, "Brochette de bœuf style kafta", 1, 0));
        produits.add(new Produit(6, "Rosettes de bœuf aux légumes, fromage et jambon", 1, 0));
        produits.add(new Produit(7, "Bœuf haché maigre, format familial", 1, 0));
        produits.add(new Produit(8, "Galette de bœuf haché maigre", 1, 0));
        produits.add(new Produit(9, "Bifteck d'aloyau", 1, 0));
        produits.add(new Produit(10, "Biftecks d'aloyau, format familial", 1, 0));
        produits.add(new Produit(11, "Bifteck de côtes", 1, 0));
        produits.add(new Produit(12, "Biftecks de côtes, format familial", 1, 0));
        produits.add(new Produit(13, "Bifteck de contre-filet", 1, 0));
        produits.add(new Produit(14, "Bifteck de faux-filet", 1, 0));
        produits.add(new Produit(15, "Biftecks de culotte de haut de surlonge, Angus", 1, 0));
        produits.add(new Produit(16, "Bavette de bœuf, Angus", 1, 0));
        produits.add(new Produit(21, "Cuisses de poulet sans dos, format familial", 1, 0));
        produits.add(new Produit(22, "Tournedos de poitrine de poulet", 1, 0));
        produits.add(new Produit(23, "Tournedos de poitrine de poulet assaisonés et enrobés de bacon surgelés", 1, 0));
        produits.add(new Produit(24, "Brochettes de filet de porc avec légumes", 1, 0));
        produits.add(new Produit(25, "Brochettes de médaillons de filet de porc bardés de bacon", 1, 0));
        produits.add(new Produit(26, "Brochette de porc style kafta", 1, 0));
        produits.add(new Produit(27, "Tournedos de porc bardés de bacon", 1, 0));
        produits.add(new Produit(28, "Filet de porc", 1, 0));
        produits.add(new Produit(29, "Tranches de surlonge de porc désossées, format familial", 1, 0));
        produits.add(new Produit(30, "Côtelettes de faux-filet de porc tranchées", 1, 0));
        produits.add(new Produit(31, "Côtelettes de porc BBQ désossées", 1, 0));
        produits.add(new Produit(32, "Côtelettes de porc coupe du centre, format familial", 1, 0));
        produits.add(new Produit(33, "Côtelettes de porc coupe du centre désossées, format familial", 1, 0));
        produits.add(new Produit(34, "Trio de côtelettes de porc", 1, 0));
        produits.add(new Produit(35, "Côtelettes de longe de porc coupe hôtel", 1, 0));
        produits.add(new Produit(36, "Côtelettes de porc papillon, format familial", 1, 0));
        produits.add(new Produit(41, "Filet de porc farci aux asperges et fromage", 1, 0));
        produits.add(new Produit(42, "Poitrine de poulet farcie aux épinards et au fromage", 1, 0));
        produits.add(new Produit(43, "Filet de porc farci au brie et canneberges", 1, 0));
        produits.add(new Produit(44, "Filet de porc farci au feta et à la bruschetta", 1, 0));
        produits.add(new Produit(45, "Saucisses italiennes douces", 1, 0));
        produits.add(new Produit(46, "Saucisses italiennes fortes", 1, 0));
        produits.add(new Produit(47, "Saucisses de chorizo", 1, 0));
        produits.add(new Produit(48, "Saucisses portugaises", 1, 0));
        produits.add(new Produit(49, "Saucisses de porc à la bière", 1, 0));
        produits.add(new Produit(50, "Saucisses au miel et à la moutarde", 1, 0));
        produits.add(new Produit(51, "Saucisses aux bleuets et à l'érable", 1, 0));
        produits.add(new Produit(52, "Saucisses aux pommes et oignons caramélisés", 1, 0));
        produits.add(new Produit(53, "Saucisses à la poutine", 1, 0));
        produits.add(new Produit(54, "Saucisses tacos", 1, 0));
        produits.add(new Produit(55, "Saucisses pizza", 1, 0));
        produits.add(new Produit(56, "Saucisses à l'orientale", 1, 0));
        produits.add(new Produit(61, "Burgers de surlonge de bœuf surgelés, La Boucherie", 1, 0));
        produits.add(new Produit(62, "Burgers de bœuf BBQ gigantesques surgelés, La Boucherie", 1, 0));
        produits.add(new Produit(63, "Burgers de bœuf gigantesques aux épices pour bifteck de Montréal surgelés, La Boucherie", 1, 0));
        produits.add(new Produit(64, "Burgers farcis au bacon et au cheddar surgelés", 1, 0));
        produits.add(new Produit(65, "Burgers farcis au fromage suisse et champignon portobello", 1, 0));
        produits.add(new Produit(66, "Burgers de kangourou surgelés", 1, 0));
        produits.add(new Produit(67, "Brochettes de poulet assaisonnées avec légumes", 1, 0));
        produits.add(new Produit(68, "Brochettes de poulet en marinade shish taouk", 1, 0));
        produits.add(new Produit(69, "Brochettes de médaillons de poulet bardés assaisonnés", 1, 0));
        produits.add(new Produit(70, "Poitrine de poulet en marinade shish taouk", 1, 0));
        produits.add(new Produit(71, "Poitrine de poulet en marinade souvlaki", 1, 0));
        produits.add(new Produit(72, "Poitrine de poulet assaisonnée, parée et désossée", 1, 0));
        produits.add(new Produit(73, "Souvlakis de poulet marinés", 1, 0));
        produits.add(new Produit(74, "Hauts de cuisse de poulet désossés en marinade shish taouk", 1, 0));
        produits.add(new Produit(75, "Hauts de cuisse de poulet désossés en marinade souvlaki", 1, 0));
        produits.add(new Produit(76, "Souvlakis de poulet assaisonnés", 1, 0));
        produits.add(new Produit(81, "Bifteck français shawarma", 1, 0));
        produits.add(new Produit(82, "Souvlakis de bœuf assaisonnés", 1, 0));
        produits.add(new Produit(83, "Souvlakis de bœuf marinés", 1, 0));
        produits.add(new Produit(84, "Biftecks de tournedos au poivre", 1, 0));
        produits.add(new Produit(85, "Brochettes de filet de porc avec légumes assaisonnées", 1, 0));
        produits.add(new Produit(86, "Brochettes de médaillons de filet de porc bardés de bacon assaisonnées", 1, 0));
        produits.add(new Produit(87, "Souvlakis de porc marinés", 1, 0));
        produits.add(new Produit(88, "Souvlakis de porc assaisonnés", 1, 0));
        produits.add(new Produit(89, "Côtelettes de porc BBQ désossées assaisonnées", 1, 0));
        produits.add(new Produit(90, "Côtelettes de porc coupe du centre désossées et assaisonnées", 1, 0));
        produits.add(new Produit(91, "Côtelettes de faux-filet de porc tranchées et assaisonnées", 1, 0));
        produits.add(new Produit(92, "Côtelette de porc coupe du centre assaisonnée", 1, 0));
        produits.add(new Produit(93, "Côtelettes de porc coupe hôtel assaisonnées", 1, 0));
        produits.add(new Produit(94, "Filet de porc en marinade souvlaki", 1, 0));
        produits.add(new Produit(95, "Filet de porc assaisonné", 1, 0));
        produits.add(new Produit(96, "Filet de porc en marinade shish taouk", 1, 0));
        produits.add(new Produit(101, "Bœuf haché mi-maigre, format familial", 1, 0));
        produits.add(new Produit(102, "Filets de porc, format familial", 1, 0));
        produits.add(new Produit(103, "Rosbif français d'intérieur de ronde non-bardé", 1, 0));
        produits.add(new Produit(104, "Bœuf pour fondue chinoise surgelé", 1, 0));
        produits.add(new Produit(105, "Cubes de bœuf bourguignon, format familial", 1, 0));
        produits.add(new Produit(106, "Rosbif de filet mignon", 1, 0));
        produits.add(new Produit(107, "Cuisses de poulet avec dos, format familial", 1, 0));
        produits.add(new Produit(108, "Rosbif de côtes croisées désossé", 1, 0));
        produits.add(new Produit(109, "Bifteck de filet mignon", 1, 0));
        produits.add(new Produit(110, "Mélange de bœuf et de porc hachés maigres, format familial", 1, 0));
        produits.add(new Produit(111, "Porc haché extra-maigre", 1, 0));
        produits.add(new Produit(112, "Saucisses fumées originales", 1, 0));
        produits.add(new Produit(113, "Boeuf pour fondue chinoise", 1, 0));
        produits.add(new Produit(114, "Bifteck français", 1, 0));
        produits.add(new Produit(115, "Poulet frais entier", 1, 0));
        produits.add(new Produit(116, "Bacon avec 50% moins de sel", 1, 0));
        produits.add(new Produit(121, "Poulets frais entiers de catégorie A, format familial", 1, 0));
        produits.add(new Produit(122, "Hauts de cuisse de poulet désossés et sans peau", 1, 0));
        produits.add(new Produit(123, "Viandes de bœuf, veau et porc hachées maigres", 1, 0));
        produits.add(new Produit(124, "Biftecks de tournedos non bardés, format familial", 1, 0));
        produits.add(new Produit(125, "Rôti de longe de porc coupe du centre désossée", 1, 0));
        produits.add(new Produit(126, "Côtes de dos de porc classiques cuites", 1, 0));
        produits.add(new Produit(127, "Veau de grain haché maigre, format familial", 1, 0));
        produits.add(new Produit(128, "Bacon à saveur d'érable", 1, 0));
        produits.add(new Produit(129, "Côtelettes de porc coupe du centre", 1, 0));
        produits.add(new Produit(130, "Poitrines de poulet avec dos, format familial", 1, 0));
        produits.add(new Produit(131, "Biftecks de tournedos non bardés", 1, 0));
        produits.add(new Produit(132, "Ailes de poulet Buffalo surgelées", 1, 0));
        produits.add(new Produit(133, "Jambon fumé Forêt-Noire extra maigre", 1, 0));
        produits.add(new Produit(134, "Bifteck au poivre", 1, 0));
        produits.add(new Produit(135, "Tranches de foie de veau de grain", 1, 0));
        produits.add(new Produit(136, "Cheval haché maigre", 1, 0));
        produits.add(new Produit(141, "Poitrine de poulet avec dos", 1, 0));
        produits.add(new Produit(142, "Bacon en tranches épaisses", 1, 0));
        produits.add(new Produit(143, "Demi-longe de porc bout de côtes désossée", 1, 0));
        produits.add(new Produit(144, "Poitrine de dindon désossée et sans peau", 1, 0));
        produits.add(new Produit(145, "Saucisses fumées au poulet", 1, 0));
        produits.add(new Produit(146, "Cubes de cuisse de boeuf pour fondue", 1, 0));
        produits.add(new Produit(147, "Pâté au poulet surgelé", 1, 0));
        produits.add(new Produit(148, "Pilons de poulet", 1, 0));
        produits.add(new Produit(149, "Rôti d'intérieur de ronde de bœuf", 1, 0));
        produits.add(new Produit(150, "Côtelettes de porc coupe du centre désossées, brunir et servir", 1, 0));
        produits.add(new Produit(151, "Bifteck de haut de surlonge désossé sans culotte", 1, 0));
        produits.add(new Produit(152, "Porc pour fondue chinoise surgelé", 1, 0));
        produits.add(new Produit(153, "Poulet entier", 1, 0));
        produits.add(new Produit(154, "Cuisses de poulet avec dos", 1, 0));
        produits.add(new Produit(155, "Duo de côtelettes de porc", 1, 0));
        produits.add(new Produit(156, "Bifteck d'intérieur de ronde à mariner", 1, 0));
        produits.add(new Produit(161, "Lanières de cuisse de bœuf", 1, 0));
        produits.add(new Produit(162, "Saucisses italienne douce", 1, 0));
        produits.add(new Produit(163, "Poulet de grain entier, Naturalia", 1, 0));
        produits.add(new Produit(164, "Cubes de bœuf désossés pour ragoût", 1, 0));
        produits.add(new Produit(165, "Ailes de poulet BBQ surgelées", 1, 0));
        produits.add(new Produit(166, "Saucisses au porc et au bœuf légères", 1, 0));
        produits.add(new Produit(167, "Lanières de poitrine de poulet", 1, 0));
        produits.add(new Produit(168, "Escalopes de poulet", 1, 0));
        produits.add(new Produit(169, "Poitrines de poulet désossées", 1, 0));
        produits.add(new Produit(170, "Osso bucco de porc", 1, 0));
        produits.add(new Produit(171, "Rôti de poire intérieur de ronde de bœuf", 1, 0));
        produits.add(new Produit(172, "Côtelettes de porc papillon", 1, 0));
        produits.add(new Produit(173, "Côtelettes de porc coupe du centre, brunir et servir", 1, 0));
        produits.add(new Produit(174, "Ailes de poulet paprika fumé et érable surgelées", 1, 0));
        produits.add(new Produit(175, "Filet mignon de bœuf entier", 1, 0));
        produits.add(new Produit(176, "Combo de saucisse italienne et allemande", 1, 0));

        return produits;
    }
    static Produits creeListeProduitFruitsEtLegumes(){
        Produits produits = new Produits();
        produits.add(new Produit(1, "Pomme, McIntosh", 1, 0));
        produits.add(new Produit(2, "Courge musquée", 1, 0));
        produits.add(new Produit(3, "Courge spaghetti", 1, 0));
        produits.add(new Produit(4, "Courge poivrée", 1, 0));
        produits.add(new Produit(5, "Courge buttercup", 1, 0));
        produits.add(new Produit(6, "Citrouille", 1, 0));
        produits.add(new Produit(7, "Courge delicata", 1, 0));
        produits.add(new Produit(8, "Courge Sweet Dumpling", 1, 0));
        produits.add(new Produit(9, "Banane", 1, 0));
        produits.add(new Produit(10, "Concombre anglais", 1, 0));
        produits.add(new Produit(11, "Champignons blancs", 1, 0));
        produits.add(new Produit(12, "Framboises", 1, 0));
        produits.add(new Produit(13, "Tomate rouge de serre", 1, 0));
        produits.add(new Produit(14, "Tomates rouges en grappe", 1, 0));
        produits.add(new Produit(15, "Carottes miniatures coupées", 1, 0));
        produits.add(new Produit(16, "Oignons verts", 1, 0));
        produits.add(new Produit(21, "Tomates raisins", 1, 0));
        produits.add(new Produit(22, "Carottes nantaises douces", 1, 0));
        produits.add(new Produit(23, "Banane biologique", 1, 0));
        produits.add(new Produit(24, "Cantaloup", 1, 0));
        produits.add(new Produit(25, "Chou vert", 1, 0));
        produits.add(new Produit(26, "Tomate rouge de serre", 1, 0));
        produits.add(new Produit(27, "Tomate rose de serre", 1, 0));
        produits.add(new Produit(28, "Pomme, Granny Smith", 1, 0));
        produits.add(new Produit(29, "Poivron vert", 1, 0));
        produits.add(new Produit(30, "Clémentine", 1, 0));
        produits.add(new Produit(31, "Ail", 1, 0));
        produits.add(new Produit(32, "Patate douce", 1, 0));
        produits.add(new Produit(33, "Laitue à feuilles vertes", 1, 0));
        produits.add(new Produit(34, "Jeunes épinards", 1, 0));
        produits.add(new Produit(35, "Oignon espagnol", 1, 0));
        produits.add(new Produit(36, "Quartier de melon d'eau sans pépins", 1, 0));
        produits.add(new Produit(41, "Mélange de salade printanier", 1, 0));
        produits.add(new Produit(42, "Laitue romaine", 1, 0));
        produits.add(new Produit(43, "Jeunes épinards", 1, 0));
        produits.add(new Produit(44, "Roquette", 1, 0));
        produits.add(new Produit(45, "Persil frisé", 1, 0));
        produits.add(new Produit(46, "Pomme de terre Russet", 1, 0));
        produits.add(new Produit(47, "Coriandre", 1, 0));
        produits.add(new Produit(48, "Ananas entier tranché", 1, 0));
        produits.add(new Produit(49, "Pommes de terre rouges", 1, 0));
        produits.add(new Produit(50, "Kiwi", 1, 0));
        produits.add(new Produit(51, "Sac d'épinards", 1, 0));
        produits.add(new Produit(52, "Laitue Boston vivante de serre en dôme", 1, 0));
        produits.add(new Produit(53, "Pommes de terre à chair jaune lavées", 1, 0));
        produits.add(new Produit(54, "Persil italien", 1, 0));
        produits.add(new Produit(55, "Pommes de terre russet", 1, 0));
        produits.add(new Produit(56, "Bleuets", 1, 0));
        produits.add(new Produit(61, "Basilic en emballage", 1, 0));
        produits.add(new Produit(62, "Mélange de salade San Marino", 1, 0));
        produits.add(new Produit(63, "Pomme jaune, Délicieuse", 1, 0));
        produits.add(new Produit(64, "Pois mange-tout", 1, 0));
        produits.add(new Produit(65, "Mélange de salade César avec garnitures", 1, 0));
        produits.add(new Produit(66, "Pommes de terre grelots fraîches, Terrific Trio", 1, 0));
        produits.add(new Produit(67, "Fenouil", 1, 0));
        produits.add(new Produit(68, "Pommes de terre grelots fraîches, Boomer Gold", 1, 0));
        produits.add(new Produit(69, "Ananas tropical gold", 1, 0));
        produits.add(new Produit(70, "Bouquet de ciboulette en emballage", 1, 0));
        produits.add(new Produit(71, "Courgette", 1, 0));
        produits.add(new Produit(72, "Petites pommes de terre à chair jaune lavées", 1, 0));
        produits.add(new Produit(73, "Oignon blanc", 1, 0));
        produits.add(new Produit(74, "Coriandre en emballage", 1, 0));
        produits.add(new Produit(75, "Basilic en pot", 1, 0));
        produits.add(new Produit(76, "Pommes de terre grelots fraîches, Blushing Belle", 1, 0));
        produits.add(new Produit(81, "Laitue à feuilles rouges", 1, 0));
        produits.add(new Produit(82, "Pomme, Honeycrisp", 1, 0));
        produits.add(new Produit(83, "Mélange de salade César avec garnitures", 1, 0));
        produits.add(new Produit(84, "Salade de fruits régulière", 1, 0));
        produits.add(new Produit(85, "Tofu pasteurisé régulier", 1, 0));
        produits.add(new Produit(86, "Tomates cerises", 1, 0));
        produits.add(new Produit(87, "Haricots verts", 1, 0));
        produits.add(new Produit(88, "Oignons rouges", 1, 0));
        produits.add(new Produit(89, "Pomme, Spartan", 1, 0));
        produits.add(new Produit(90, "Pomme grenade", 1, 0));
        produits.add(new Produit(91, "Mini melon d'eau sans pépins", 1, 0));
        produits.add(new Produit(92, "Pois sucrés", 1, 0));
        produits.add(new Produit(93, "Jeunes épinards biologiques", 1, 0));
        produits.add(new Produit(94, "Ail haché", 1, 0));
        produits.add(new Produit(95, "Feuilles de menthe en emballage", 1, 0));
        produits.add(new Produit(96, "Mélange de légumes coupés pour soupes", 1, 0));
        produits.add(new Produit(101, "Citron", 1, 0));
        produits.add(new Produit(102, "Poireaux tranchés et lavés", 1, 0));
        produits.add(new Produit(103, "Carottes biologiques", 1, 0));
        produits.add(new Produit(104, "Gros pamplemousse", 1, 0));
        produits.add(new Produit(105, "Thym en emballage", 1, 0));
        produits.add(new Produit(106, "Tartinade de tofu", 1, 0));
        produits.add(new Produit(107, "Chou rouge", 1, 0));
        produits.add(new Produit(108, "Mini poivrons doux", 1, 0));
        produits.add(new Produit(109, "Aneth en emballage", 1, 0));
        produits.add(new Produit(110, "Mélange bébé chou frisé", 1, 0));
        produits.add(new Produit(111, "Pommes de terre parisiennes", 1, 0));
        produits.add(new Produit(112, "Plateau de 4 légumes avec trempette ranch", 1, 0));
        produits.add(new Produit(113, "Mélange baie sublime", 1, 0));
        produits.add(new Produit(114, "Mélange de légumes coupés pour sauce à spaghetti", 1, 0));
        produits.add(new Produit(115, "Céleri biologique", 1, 0));
        produits.add(new Produit(116, "Poireau", 1, 0));
        produits.add(new Produit(121, "Piment jalapeno", 1, 0));
        produits.add(new Produit(122, "Salade mélange américain", 1, 0));
        produits.add(new Produit(123, "Tomates rouges en grappe biologiques", 1, 0));
        produits.add(new Produit(124, "Poire Rocha", 1, 0));
        produits.add(new Produit(125, "Tomate italienne", 1, 0));
        produits.add(new Produit(126, "Mélange de salade oriental", 1, 0));
        produits.add(new Produit(127, "Ail haché", 1, 0));
        produits.add(new Produit(128, "Mélange pour salade romaine classique", 1, 0));
        produits.add(new Produit(129, "Mélange pour salade César", 1, 0));
        produits.add(new Produit(130, "Sac de radis", 1, 0));
        produits.add(new Produit(131, "Canneberges séchées et sucrées", 1, 0));
        produits.add(new Produit(132, "Cantaloup en morceaux", 1, 0));
        produits.add(new Produit(133, "Cœurs de céleri", 1, 0));
        produits.add(new Produit(134, "Julienne de légumes", 1, 0));
        produits.add(new Produit(135, "Mangue rouge", 1, 0));
        produits.add(new Produit(136, "Couronne de brocoli enveloppée", 1, 0));
        produits.add(new Produit(141, "Mini tomates Kumato", 1, 0));
        produits.add(new Produit(142, "Pamplemousse", 1, 0));
        produits.add(new Produit(143, "Tofu extra ferme", 1, 0));
        produits.add(new Produit(144, "Pommes de terre grelots à l'ail et aux fines herbes avec kit à griller", 1, 0));
        produits.add(new Produit(145, "Champignons porteenies", 1, 0));
        produits.add(new Produit(146, "Avocats biologiques", 1, 0));
        produits.add(new Produit(147, "Plateau de 5 légumes", 1, 0));
        produits.add(new Produit(148, "Cœurs de laitue romaine biologiques", 1, 0));
        produits.add(new Produit(149, "Noix de Grenoble crues", 1, 0));
        produits.add(new Produit(150, "Plateau de fruits Le farouche", 1, 0));
        produits.add(new Produit(151, "Mélange de salade Grecque avec garnitures", 1, 0));
        produits.add(new Produit(152, "Plateau de mélange de crudités avec trempette ranch", 1, 0));
        produits.add(new Produit(153, "Plateau de fruits", 1, 0));
        produits.add(new Produit(154, "Betteraves", 1, 0));
        produits.add(new Produit(155, "Poivron rouge de champs", 1, 0));
        produits.add(new Produit(156, "Trio de pommes", 1, 0));
        produits.add(new Produit(161, "Sac de pommes, Gala", 1, 0));
        produits.add(new Produit(162, "Tofu mou", 1, 0));
        produits.add(new Produit(163, "Pommes de terre grelots fraîches à l'ail et au persil", 1, 0));
        produits.add(new Produit(164, "Dattes séchées dénoyautées", 1, 0));
        produits.add(new Produit(165, "Aubergine", 1, 0));
        produits.add(new Produit(166, "Sac de limes", 1, 0));
        produits.add(new Produit(167, "Salade de fruits régulière", 1, 0));
        produits.add(new Produit(168, "Plateau de fruits avec trempette au chocolat", 1, 0));
        produits.add(new Produit(169, "Tomates raisins orange", 1, 0));
        produits.add(new Produit(170, "Bébé bok choy", 1, 0));
        produits.add(new Produit(171, "Luzerne biologique", 1, 0));
        produits.add(new Produit(172, "Salade de fruits de luxe", 1, 0));
        produits.add(new Produit(173, "Raisins secs de Californie naturels", 1, 0));
        produits.add(new Produit(174, "Raisins secs de Californie naturels, Mini-Paquets", 1, 0));
        produits.add(new Produit(175, "Mélange de bébé romaine biologique", 1, 0));
        produits.add(new Produit(176, "Mangue miel", 1, 0));





        return produits;
    }
}
